/* KASITU Webs Business Manager — Phase 2 */
const content=document.getElementById('appContent'),title=document.getElementById('pageTitle'),sidebar=document.getElementById('sidebar'),modal=document.getElementById('modalBackdrop'),modalTitle=document.getElementById('modalTitle'),form=document.getElementById('recordForm');
let clients=[],leads=[],quotations=[],invoices=[];
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));
const money=n=>`R${Number(n||0).toLocaleString('en-ZA',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const today=()=>new Date().toISOString().slice(0,10);
const addDays=(date,days)=>{const d=new Date(date+'T00:00:00');d.setDate(d.getDate()+days);return d.toISOString().slice(0,10)};
async function getSession(){const {data,error}=await window.kasituSupabase.auth.getSession();if(error||!data.session){window.location.replace('login.html');return null}return data.session}
async function loadData(){
 const session=await getSession();if(!session)return false;
 const [cr,lr,qr,ir]=await Promise.all([window.kasituSupabase.from('clients').select('*').order('created_at',{ascending:true}),window.kasituSupabase.from('leads').select('*').order('created_at',{ascending:false}),window.kasituSupabase.from('quotations').select('*').order('created_at',{ascending:false}),window.kasituSupabase.from('invoices').select('*').order('created_at',{ascending:false})]);
 if(cr.error||lr.error||qr.error||ir.error){console.error(cr.error||lr.error||qr.error||ir.error);content.innerHTML='<div class="panel"><h2>Database setup required</h2><p>Clients, Leads and Quotations are ready. Run the <strong>Phase 3 invoice section</strong> from <strong>supabase-schema.sql</strong> in Supabase SQL Editor, then refresh.</p></div>';return false}
 clients=cr.data.map(c=>({id:c.client_code,business:c.business_name,contact:c.contact_name||'',email:c.email||'',phone:c.phone||'',service:c.service||'',status:c.status,notes:c.notes||'',_id:c.id}));
 leads=lr.data.map(l=>({id:l.id,business:l.business_name,contact:l.contact_name||'',phone:l.phone||'',email:l.email||'',service:l.service_requested||'',status:l.status,followUp:l.follow_up_date||'',source:l.source||'',notes:l.notes||'',date:l.created_at?.slice(0,10)||''}));
 quotations=qr.data.map(q=>({...q,items:Array.isArray(q.line_items)?q.line_items:[]}));
invoices=ir.data.map(i=>({...i,items:Array.isArray(i.line_items)?i.line_items:[]}));
 return true
}
function renderDashboard(){
 title.textContent='Dashboard';const active=clients.filter(c=>c.status==='Active').length,openLeads=leads.filter(l=>!['Won','Lost'].includes(l.status)).length,approved=quotations.filter(q=>q.status==='Approved').length,outstanding=invoices.reduce((s,i)=>s+Number(i.balance_due||0),0);
 content.innerHTML=`<div class="hero-copy"><h2>Good morning, KASITU.</h2><p>Your business command centre — clients, leads and quotations in one place.</p></div>
 <div class="stats"><div class="stat"><div class="stat-label">Clients</div><div class="stat-value">${clients.length}</div><div class="stat-note">${active} active</div></div><div class="stat"><div class="stat-label">Open Leads</div><div class="stat-value">${openLeads}</div><div class="stat-note">Follow-ups to manage</div></div><div class="stat"><div class="stat-label">Quotations</div><div class="stat-value">${quotations.length}</div><div class="stat-note">${approved} approved</div></div><div class="stat"><div class="stat-label">Quoted Value</div><div class="stat-value">${money(quotations.reduce((s,q)=>s+Number(q.total||0),0))}</div><div class="stat-note">All quotation statuses</div></div><div class="stat"><div class="stat-label">Invoices</div><div class="stat-value">${invoices.length}</div><div class="stat-note">${money(outstanding)} outstanding</div></div></div>
 <div class="grid-2"><div class="panel"><div class="panel-head"><h3>Recent Clients</h3><button class="btn" data-go="clients">View all</button></div>${clientTable(clients.slice(-5).reverse())}</div><div class="panel"><div class="panel-head"><h3>Recent Quotations</h3><button class="btn" data-go="quotations">View all</button></div>${quoteMini()}</div></div></div>`;bindNavigationButtons()
}
function clientTable(rows){if(!rows.length)return '<div class="empty">No clients yet.</div>';return `<div class="table-wrap"><table class="table"><thead><tr><th>Client</th><th>Service</th><th>Status</th></tr></thead><tbody>${rows.map(c=>`<tr><td><strong>${esc(c.business)}</strong><br><span style="color:var(--muted)">${esc(c.id)}</span></td><td>${esc(c.service||'—')}</td><td><span class="badge">${esc(c.status)}</span></td></tr>`).join('')}</tbody></table></div>`}
function leadSummary(){if(!leads.length)return '<div class="empty">No leads yet.<br><br><button class="btn primary" data-add="lead">Add your first lead</button></div>';const counts={New:0,Contacted:0,Quoted:0,Won:0,Lost:0};leads.forEach(l=>counts[l.status]=(counts[l.status]||0)+1);return Object.entries(counts).map(([k,v])=>`<div style="display:flex;justify-content:space-between;padding:12px 0;border-bottom:1px solid var(--border);font-size:12px"><span>${k}</span><strong>${v}</strong></div>`).join('')}
function renderClients(filter=''){title.textContent='Clients';const rows=clients.filter(c=>`${c.business} ${c.contact} ${c.email} ${c.id}`.toLowerCase().includes(filter.toLowerCase()));content.innerHTML=`<div class="section-head"><div><h2>Clients</h2><p>Your central client register and client IDs.</p></div><div style="display:flex;gap:9px"><input id="clientSearch" class="search" placeholder="Search clients..." value="${esc(filter)}"><button class="btn primary" data-add="client">+ Add Client</button></div></div><div class="panel">${clientTableDetailed(rows)}</div>`;document.getElementById('clientSearch').addEventListener('input',e=>renderClients(e.target.value))}
function clientTableDetailed(rows){if(!rows.length)return '<div class="empty">No matching clients.</div>';return `<div class="table-wrap"><table class="table"><thead><tr><th>Client ID</th><th>Business</th><th>Contact</th><th>Service</th><th>Status</th><th></th></tr></thead><tbody>${rows.map(c=>`<tr><td>${esc(c.id)}</td><td><strong>${esc(c.business)}</strong></td><td>${esc(c.contact||'—')}<br><span style="color:var(--muted)">${esc(c.phone||c.email||'')}</span></td><td>${esc(c.service||'—')}</td><td><span class="badge">${esc(c.status)}</span></td><td><button class="btn" data-edit-client="${esc(c.id)}">Edit</button></td></tr>`).join('')}</tbody></table></div>`}
function renderLeads(filter=''){title.textContent='Leads';const rows=leads.filter(l=>`${l.business} ${l.contact} ${l.service} ${l.status}`.toLowerCase().includes(filter.toLowerCase()));content.innerHTML=`<div class="section-head"><div><h2>Lead Pipeline</h2><p>Track enquiries from first contact to won or lost.</p></div><div style="display:flex;gap:9px"><input id="leadSearch" class="search" placeholder="Search leads..." value="${esc(filter)}"><button class="btn primary" data-add="lead">+ Add Lead</button></div></div><div class="panel">${leadTable(rows)}</div>`;document.getElementById('leadSearch').addEventListener('input',e=>renderLeads(e.target.value))}
function leadTable(rows){if(!rows.length)return '<div class="empty">No leads yet. Add every genuine enquiry here so no opportunity gets forgotten.</div>';return `<div class="table-wrap"><table class="table"><thead><tr><th>Date</th><th>Business / Person</th><th>Service</th><th>Status</th><th>Follow-up</th><th></th></tr></thead><tbody>${rows.map(l=>`<tr><td>${esc(l.date||'—')}</td><td><strong>${esc(l.business)}</strong><br><span style="color:var(--muted)">${esc(l.contact||'')}</span></td><td>${esc(l.service||'—')}</td><td><span class="badge">${esc(l.status)}</span></td><td>${esc(l.followUp||'—')}</td><td><button class="btn" data-edit-lead="${esc(l.id)}">Edit</button></td></tr>`).join('')}</tbody></table></div>`}

function invoiceStatus(s){return `<span class="invoice-status ${String(s||'Draft').toLowerCase().replace(/\\s+/g,'-')}">${esc(s||'Draft')}</span>`}
function invoiceMini(){if(!invoices.length)return '<div class="empty">No invoices yet.<br><br><button class="btn primary" data-add="invoice">Create first invoice</button></div>';return invoices.slice(0,5).map(i=>`<div class="invoice-card"><div class="invoice-card-head"><div><div class="invoice-number">${esc(i.invoice_number)}</div><strong>${esc(i.client_name)}</strong></div><div style="text-align:right"><div class="invoice-total">${money(i.total)}</div>${invoiceStatus(i.status)}</div></div></div>`).join('')}
function renderInvoices(filter=''){title.textContent='Invoices';const rows=invoices.filter(i=>`${i.invoice_number} ${i.client_name} ${i.status}`.toLowerCase().includes(filter.toLowerCase()));content.innerHTML=`<div class="section-head"><div><h2>Invoices</h2><p>Create invoices from quotations, track balances and payment status.</p></div><div class="quote-toolbar"><input id="invoiceSearch" class="search" placeholder="Search invoices..." value="${esc(filter)}"><button class="btn primary" data-add="invoice">+ New Invoice</button></div></div><div class="panel">${invoiceTable(rows)}</div>`;document.getElementById('invoiceSearch').addEventListener('input',e=>renderInvoices(e.target.value))}
function invoiceTable(rows){if(!rows.length)return '<div class="empty">No invoices found. Create an invoice from a quotation.</div>';return `<div class="table-wrap"><table class="table"><thead><tr><th>Invoice</th><th>Client</th><th>Date</th><th>Due</th><th>Status</th><th>Total</th><th>Balance</th><th></th></tr></thead><tbody>${rows.map(i=>`<tr><td><strong>${esc(i.invoice_number)}</strong></td><td>${esc(i.client_name)}</td><td>${esc(i.invoice_date||'—')}</td><td>${esc(i.due_date||'—')}</td><td>${invoiceStatus(i.status)}</td><td><strong>${money(i.total)}</strong></td><td><strong>${money(i.balance_due)}</strong></td><td><button class="btn" data-edit-invoice="${esc(i.id)}">Edit</button></td></tr>`).join('')}</tbody></table></div>`}
function quotationOptions(selected=''){return '<option value="">Start without a quotation...</option>'+quotations.map(q=>`<option value="${esc(q.id)}" ${q.id===selected?'selected':''}>${esc(q.quote_number)} — ${esc(q.client_name)} — ${money(q.total)}</option>`).join('')}
function defaultInvoiceItems(i){return i?.items?.length?i.items:[{description:'',quantity:1,unit_price:0}]}
function invoiceForm(i={}){
 i=i||{};const valid=i.due_date||addDays(i.invoice_date||today(),7);
 return `<div class="form-grid"><div class="field"><label>Quotation</label><select name="quotation_id">${quotationOptions(i.quotation_id||'')}</select></div><div class="field"><label>Invoice number</label><input name="invoice_number" value="${esc(i.invoice_number||'')}" placeholder="Auto-generated on save" readonly></div><div class="field"><label>Invoice date *</label><input type="date" name="invoice_date" value="${esc(i.invoice_date||today())}" required></div><div class="field"><label>Due date</label><input type="date" name="due_date" value="${esc(valid)}"></div><div class="field"><label>Status</label><select name="status">${['Draft','Sent','Partially Paid','Paid','Overdue','Cancelled'].map(x=>`<option ${x===(i.status||'Draft')?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Amount paid (R)</label><input name="amount_paid" type="number" min="0" step="0.01" value="${Number(i.amount_paid||0).toFixed(2)}"></div><div class="field"><label>Discount (R)</label><input name="discount" type="number" min="0" step="0.01" value="${Number(i.discount||0).toFixed(2)}"></div><div class="field"><label>VAT rate (%)</label><input name="vat_rate" type="number" min="0" max="100" step="0.01" value="${Number(i.vat_rate||0)}"></div></div><div style="margin-top:20px"><div class="panel-head"><h3>Line items</h3><button type="button" class="btn" id="addInvoiceLine">+ Add item</button></div><div class="line-items" id="invoiceLines">${itemRows(defaultInvoiceItems(i)).replaceAll('name="item_qty"','name="invoice_qty"').replaceAll('name="item_price"','name="invoice_price"').replaceAll('name="item_description"','name="invoice_description"').replaceAll('name="item_total"','name="invoice_total"')}</div></div><div class="quote-summary" id="invoiceSummary"></div><div class="field" style="margin-top:20px"><label>Notes</label><textarea name="notes" placeholder="Optional invoice notes">${esc(i.notes||'')}</textarea></div><div class="field" style="margin-top:14px"><label>Terms & conditions</label><textarea name="terms" placeholder="Payment terms, due date, bank/payment details, etc.">${esc(i.terms||'Payment is due by the due date shown above. Please retain the invoice number as your payment reference.')}</textarea></div><div class="form-actions"><button type="button" class="btn" id="cancelModal">Cancel</button><button class="btn primary">Save Invoice</button></div>`}
function collectInvoiceItems(){return [...form.querySelectorAll('[data-line-row]')].map(row=>({description:row.querySelector('[name="invoice_description"]').value.trim(),quantity:Number(row.querySelector('[name="invoice_qty"]').value||0),unit_price:Number(row.querySelector('[name="invoice_price"]').value||0)})).filter(i=>i.description||i.unit_price>0)}
function calculateInvoice(){const items=collectInvoiceItems(),subtotal=items.reduce((s,i)=>s+i.quantity*i.unit_price,0),discount=Math.max(0,Number(form.querySelector('[name="discount"]')?.value||0)),taxable=Math.max(0,subtotal-discount),vatRate=Math.max(0,Number(form.querySelector('[name="vat_rate"]')?.value||0)),vat=taxable*vatRate/100,total=taxable+vat,paid=Math.min(total,Math.max(0,Number(form.querySelector('[name="amount_paid"]')?.value||0))),balance=Math.max(0,total-paid);form.querySelector('#invoiceSummary').innerHTML=`<div class="quote-summary-row"><span>Subtotal</span><strong>${money(subtotal)}</strong></div><div class="quote-summary-row"><span>Discount</span><strong>− ${money(discount)}</strong></div><div class="quote-summary-row"><span>VAT (${vatRate.toFixed(2)}%)</span><strong>${money(vat)}</strong></div><div class="quote-summary-row total"><span>Total</span><strong>${money(total)}</strong></div><div class="quote-summary-row"><span>Amount paid</span><strong>${money(paid)}</strong></div><div class="quote-summary-row"><span>Balance due</span><strong>${money(balance)}</strong></div>`;form.querySelectorAll('[data-line-row]').forEach(row=>{const qty=Number(row.querySelector('[name="invoice_qty"]').value||0),price=Number(row.querySelector('[name="invoice_price"]').value||0);row.querySelector('[name="invoice_total"]').value=money(qty*price)});return {items,subtotal,discount,vatRate,vat,total,paid,balance}}
async function nextInvoiceNumber(session){const {data,error}=await window.kasituSupabase.from('invoices').select('invoice_number').eq('owner_id',session.user.id);if(error)throw error;const nums=(data||[]).map(r=>Number(String(r.invoice_number||'').match(/^KAS-I-\\d{4}-(\\d+)$/)?.[1]||0)).filter(Number.isFinite);return `KAS-I-${new Date().getFullYear()}-${String(Math.max(0,...nums)+1).padStart(3,'0')}`}
const isUuid=v=>/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(String(v||''));
async function saveInvoice(existing){const session=await getSession();if(!session)return;const v=values(),calc=calculateInvoice();const quotationId=isUuid(v.quotation_id)?v.quotation_id:null;let quote=quotationId?quotations.find(q=>q.id===quotationId):null;let client=quote&&isUuid(quote.client_id)?clients.find(c=>c._id===quote.client_id):null;if(!client&&existing&&isUuid(existing.client_id))client=clients.find(c=>c._id===existing.client_id);if(!client){alert('The selected quotation is missing a valid client. Please close this invoice, open KAS-Q-2026-001, confirm its client, then click Invoice again.');return}if(!isUuid(client._id)){alert('The client record has an invalid UUID. Please edit/save the client first, then create the invoice again.');return}if(!calc.items.length){alert('Add at least one invoice item.');return}let invoiceNumber=existing?.invoice_number;if(!invoiceNumber)try{invoiceNumber=await nextInvoiceNumber(session)}catch(e){alert(e.message);return}let status=v.status;if(calc.paid>=calc.total&&calc.total>0)status='Paid';else if(calc.paid>0&&status==='Paid')status='Partially Paid';const payload={owner_id:session.user.id,invoice_number:invoiceNumber,quotation_id:quote?.id||null,client_id:client._id,client_code:client.id,client_name:client.business,client_contact:client.contact||null,client_email:client.email||null,client_phone:client.phone||null,invoice_date:v.invoice_date||today(),due_date:v.due_date||null,status,line_items:calc.items,subtotal:calc.subtotal,discount:calc.discount,vat_rate:calc.vatRate,vat_amount:calc.vat,total:calc.total,amount_paid:calc.paid,balance_due:calc.balance,notes:v.notes||null,terms:v.terms||null};const result=existing?await window.kasituSupabase.from('invoices').update(payload).eq('id',existing.id):await window.kasituSupabase.from('invoices').insert(payload);if(result.error){alert(result.error.message);return}await loadData();closeModal();renderInvoices()}
function quoteStatus(s){return `<span class="quote-status ${String(s||'Draft').toLowerCase()}">${esc(s||'Draft')}</span>`}
function quoteMini(){if(!quotations.length)return '<div class="empty">No quotations yet.<br><br><button class="btn primary" data-add="quotation">Create first quotation</button></div>';return quotations.slice(0,5).map(q=>`<div class="quote-card"><div class="quote-card-head"><div><div class="quote-number">${esc(q.quote_number)}</div><strong>${esc(q.client_name)}</strong></div><div style="text-align:right"><div class="quote-total">${money(q.total)}</div>${quoteStatus(q.status)}</div></div></div>`).join('')}
function renderQuotations(filter=''){title.textContent='Quotations';const rows=quotations.filter(q=>`${q.quote_number} ${q.client_name} ${q.status}`.toLowerCase().includes(filter.toLowerCase()));content.innerHTML=`<div class="section-head"><div><h2>Quotations</h2><p>Create, track and edit professional quotations.</p></div><div class="quote-toolbar"><input id="quoteSearch" class="search" placeholder="Search quotations..." value="${esc(filter)}"><button class="btn primary" data-add="quotation">+ New Quotation</button></div></div><div class="panel">${quoteTable(rows)}</div>`;document.getElementById('quoteSearch').addEventListener('input',e=>renderQuotations(e.target.value))}
function quoteTable(rows){if(!rows.length)return '<div class="empty">No quotations found. Create your first quotation.</div>';return `<div class="table-wrap"><table class="table"><thead><tr><th>Quote</th><th>Client</th><th>Date</th><th>Valid until</th><th>Status</th><th>Total</th><th></th></tr></thead><tbody>${rows.map(q=>`<tr><td><strong>${esc(q.quote_number)}</strong></td><td>${esc(q.client_name)}</td><td>${esc(q.quote_date||'—')}</td><td>${esc(q.valid_until||'—')}</td><td>${quoteStatus(q.status)}</td><td><strong>${money(q.total)}</strong></td><td><button class="btn" data-edit-quote="${esc(q.id)}">Edit</button> <button class="btn" data-create-invoice="${esc(q.id)}">Invoice</button></td></tr>`).join('')}</tbody></table></div>`}
function clientOptions(selected=''){return '<option value="">Select a client...</option>'+clients.map(c=>`<option value="${esc(c._id)}" ${c._id===selected?'selected':''}>${esc(c.id)} — ${esc(c.business)}</option>`).join('')}
function defaultItems(q){return q?.items?.length?q.items:[{description:'Business Website',quantity:1,unit_price:4999}]}
function itemRows(items){return items.map(i=>`<div class="line-item" data-line-row><div class="field line-description"><label>Item / Service</label><input name="item_description" value="${esc(i.description||'')}"></div><div class="field"><label>Qty</label><input name="item_qty" type="number" min="1" step="1" value="${Number(i.quantity||1)}"></div><div class="field"><label>Unit price</label><input name="item_price" type="number" min="0" step="0.01" value="${Number(i.unit_price||0).toFixed(2)}"></div><div class="field"><label>Line total</label><input name="item_total" readonly value="${money(Number(i.quantity||1)*Number(i.unit_price||0))}"></div><button type="button" class="btn line-remove" data-remove-line aria-label="Remove item">×</button></div>`).join('')}
function quoteForm(q={}){
 q=q||{};const valid=q.valid_until||addDays(q.quote_date||today(),14);
 return `<div class="form-grid"><div class="field"><label>Client *</label><select name="client_id" required>${clientOptions(q.client_id||'')}</select></div><div class="field"><label>Quotation number</label><input name="quote_number" value="${esc(q.quote_number||'')}" placeholder="Auto-generated on save" readonly></div><div class="field"><label>Quotation date *</label><input type="date" name="quote_date" value="${esc(q.quote_date||today())}" required></div><div class="field"><label>Valid until</label><input type="date" name="valid_until" value="${esc(valid)}"></div><div class="field"><label>Status</label><select name="status">${['Draft','Sent','Approved','Rejected','Expired'].map(x=>`<option ${x===(q.status||'Draft')?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Deposit %</label><input name="deposit_rate" type="number" min="0" max="100" step="0.01" value="${Number(q.deposit_rate??50)}"></div><div class="field"><label>Discount (R)</label><input name="discount" type="number" min="0" step="0.01" value="${Number(q.discount||0).toFixed(2)}"></div><div class="field"><label>VAT rate (%)</label><input name="vat_rate" type="number" min="0" max="100" step="0.01" value="${Number(q.vat_rate||0)}"></div></div><div style="margin-top:20px"><div class="panel-head"><h3>Line items</h3><button type="button" class="btn" id="addQuoteLine">+ Add item</button></div><div class="line-items" id="quoteLines">${itemRows(defaultItems(q))}</div></div><div class="quote-summary" id="quoteSummary"></div><div class="field" style="margin-top:20px"><label>Notes</label><textarea name="notes" placeholder="Optional notes for the client">${esc(q.notes||'')}</textarea></div><div class="field" style="margin-top:14px"><label>Terms & conditions</label><textarea name="terms" placeholder="Payment terms, delivery terms, validity, etc.">${esc(q.terms||'Payment is due according to the agreed deposit and balance schedule. Quotation is valid until the date shown above.')}</textarea></div><div class="form-actions"><button type="button" class="btn" id="cancelModal">Cancel</button><button class="btn primary">Save Quotation</button></div>`
}
function collectQuoteItems(){return [...form.querySelectorAll('[data-line-row]')].map(row=>({description:row.querySelector('[name="item_description"]').value.trim(),quantity:Number(row.querySelector('[name="item_qty"]').value||0),unit_price:Number(row.querySelector('[name="item_price"]').value||0)})).filter(i=>i.description||i.unit_price>0)}
function calculateQuote(){const items=collectQuoteItems(),subtotal=items.reduce((s,i)=>s+i.quantity*i.unit_price,0),discount=Math.max(0,Number(form.querySelector('[name="discount"]')?.value||0)),taxable=Math.max(0,subtotal-discount),vatRate=Math.max(0,Number(form.querySelector('[name="vat_rate"]')?.value||0)),vat=taxable*vatRate/100,total=taxable+vat,depositRate=Math.min(100,Math.max(0,Number(form.querySelector('[name="deposit_rate"]')?.value||0))),deposit=total*depositRate/100,balance=Math.max(0,total-deposit);form.querySelector('#quoteSummary').innerHTML=`<div class="quote-summary-row"><span>Subtotal</span><strong>${money(subtotal)}</strong></div><div class="quote-summary-row"><span>Discount</span><strong>− ${money(discount)}</strong></div><div class="quote-summary-row"><span>VAT (${vatRate.toFixed(2)}%)</span><strong>${money(vat)}</strong></div><div class="quote-summary-row total"><span>Total</span><strong>${money(total)}</strong></div><div class="quote-summary-row"><span>Deposit (${depositRate.toFixed(2)}%)</span><strong>${money(deposit)}</strong></div><div class="quote-summary-row"><span>Balance due</span><strong>${money(balance)}</strong></div>`;form.querySelectorAll('[data-line-row]').forEach(row=>{const qty=Number(row.querySelector('[name="item_qty"]').value||0),price=Number(row.querySelector('[name="item_price"]').value||0);row.querySelector('[name="item_total"]').value=money(qty*price)});return {items,subtotal,discount,vatRate,vat,total,depositRate,deposit,balance}}
function openModal(type,existing=null){
 modal.hidden=false;document.body.style.overflow='hidden';modalTitle.textContent=existing?`Edit ${type}`:`Add New ${type}`;form.innerHTML=type==='Client'?clientForm(existing):type==='Lead'?leadForm(existing):type==='Quotation'?quoteForm(existing):invoiceForm(existing);requestAnimationFrame(()=>form.querySelector('input,select')?.focus());form.onsubmit=e=>{e.preventDefault();type==='Client'?saveClient(existing):type==='Lead'?saveLead(existing):type==='Quotation'?saveQuotation(existing):saveInvoice(existing)};document.getElementById('cancelModal')?.addEventListener('click',closeModal,{once:true});
 if(type==='Quotation'){document.getElementById('addQuoteLine').addEventListener('click',()=>{document.getElementById('quoteLines').insertAdjacentHTML('beforeend',itemRows([{description:'',quantity:1,unit_price:0}]));calculateQuote()});calculateQuote();form.addEventListener('input',e=>{if(e.target.closest('#quoteLines')||['discount','vat_rate','deposit_rate'].includes(e.target.name))calculateQuote()});form.addEventListener('click',e=>{if(e.target.closest('[data-remove-line]')){e.target.closest('[data-line-row]').remove();if(!document.querySelector('[data-line-row]'))document.getElementById('quoteLines').insertAdjacentHTML('beforeend',itemRows([{description:'',quantity:1,unit_price:0}]));calculateQuote()}})}
 if(type==='Invoice'){document.getElementById('addInvoiceLine').addEventListener('click',()=>{document.getElementById('invoiceLines').insertAdjacentHTML('beforeend',itemRows([{description:'',quantity:1,unit_price:0}]).replaceAll('name="item_qty"','name="invoice_qty"').replaceAll('name="item_price"','name="invoice_price"').replaceAll('name="item_description"','name="invoice_description"').replaceAll('name="item_total"','name="invoice_total"'));calculateInvoice()});calculateInvoice();form.addEventListener('input',e=>{if(e.target.closest('#invoiceLines')||['discount','vat_rate','amount_paid'].includes(e.target.name))calculateInvoice()});form.addEventListener('click',e=>{if(e.target.closest('[data-remove-line]')){e.target.closest('[data-line-row]').remove();if(!document.querySelector('#invoiceLines [data-line-row]'))document.getElementById('invoiceLines').insertAdjacentHTML('beforeend',itemRows([{description:'',quantity:1,unit_price:0}]).replaceAll('name="item_qty"','name="invoice_qty"').replaceAll('name="item_price"','name="invoice_price"').replaceAll('name="item_description"','name="invoice_description"').replaceAll('name="item_total"','name="invoice_total"'));calculateInvoice()}})}
}
function clientForm(c={}){c=c||{};return `<div class="form-grid"><div class="field"><label>Business / Client name *</label><input name="business" required value="${esc(c.business)}"></div><div class="field"><label>Contact person</label><input name="contact" value="${esc(c.contact)}"></div><div class="field"><label>Email</label><input type="email" name="email" value="${esc(c.email)}"></div><div class="field"><label>Phone / WhatsApp</label><input name="phone" value="${esc(c.phone)}"></div><div class="field"><label>Service</label><input name="service" value="${esc(c.service)}" placeholder="e.g. Business Website"></div><div class="field"><label>Status</label><select name="status">${['Active','Prospect','Inactive'].map(x=>`<option ${x===(c.status||'Active')?'selected':''}>${x}</option>`).join('')}</select></div><div class="field" style="grid-column:1/-1"><label>Notes</label><textarea name="notes">${esc(c.notes)}</textarea></div></div><div class="form-actions"><button type="button" class="btn" id="cancelModal">Cancel</button><button class="btn primary">Save Client</button></div>`}
function leadForm(l={}){l=l||{};return `<div class="form-grid"><div class="field"><label>Business / Person *</label><input name="business" required value="${esc(l.business)}"></div><div class="field"><label>Contact person</label><input name="contact" value="${esc(l.contact)}"></div><div class="field"><label>Phone / WhatsApp</label><input name="phone" value="${esc(l.phone)}"></div><div class="field"><label>Email</label><input type="email" name="email" value="${esc(l.email)}"></div><div class="field"><label>Service requested</label><input name="service" value="${esc(l.service)}"></div><div class="field"><label>Status</label><select name="status">${['New','Contacted','Quoted','Won','Lost'].map(x=>`<option ${x===(l.status||'New')?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Follow-up date</label><input type="date" name="followUp" value="${esc(l.followUp)}"></div><div class="field"><label>Source</label><input name="source" value="${esc(l.source)}" placeholder="WhatsApp, website, referral..."></div><div class="field" style="grid-column:1/-1"><label>Notes</label><textarea name="notes">${esc(l.notes)}</textarea></div></div><div class="form-actions"><button type="button" class="btn" id="cancelModal">Cancel</button><button class="btn primary">Save Lead</button></div>`}
function values(){return Object.fromEntries(new FormData(form).entries())}
async function saveClient(existing){const v=values(),session=await getSession();if(!session)return;const base={owner_id:session.user.id,business_name:v.business,contact_name:v.contact||null,email:v.email||null,phone:v.phone||null,service:v.service||null,status:v.status,notes:v.notes||null};let result;if(existing)result=await window.kasituSupabase.from('clients').update({...base,client_code:existing.id}).eq('id',existing._id);else{const latest=await window.kasituSupabase.from('clients').select('client_code').eq('owner_id',session.user.id);if(latest.error){alert(latest.error.message);return}const used=(latest.data||[]).map(r=>Number(String(r.client_code||'').match(/^KAS-\d{4}-(\d+)$/)?.[1]||0)).filter(Number.isFinite);let next=Math.max(0,...used)+1;for(let i=0;i<5;i++){const code=`KAS-${new Date().getFullYear()}-${String(next).padStart(3,'0')}`;result=await window.kasituSupabase.from('clients').insert({...base,client_code:code});if(!result.error)break;if(!String(result.error.message||'').toLowerCase().includes('duplicate key'))break;next++}}if(result.error){alert(result.error.message);return}await loadData();closeModal();renderClients()}
async function saveLead(existing){const v=values(),session=await getSession();if(!session)return;const payload={owner_id:session.user.id,business_name:v.business,contact_name:v.contact||null,phone:v.phone||null,email:v.email||null,service_requested:v.service||null,status:v.status,follow_up_date:v.followUp||null,source:v.source||null,notes:v.notes||null};const result=existing?await window.kasituSupabase.from('leads').update(payload).eq('id',existing.id):await window.kasituSupabase.from('leads').insert(payload);if(result.error){alert(result.error.message);return}await loadData();closeModal();renderLeads()}
async function nextQuoteNumber(session){const {data,error}=await window.kasituSupabase.from('quotations').select('quote_number').eq('owner_id',session.user.id);if(error)throw error;const nums=(data||[]).map(r=>Number(String(r.quote_number||'').match(/^KAS-Q-\d{4}-(\d+)$/)?.[1]||0)).filter(Number.isFinite);return `KAS-Q-${new Date().getFullYear()}-${String(Math.max(0,...nums)+1).padStart(3,'0')}`}
async function saveQuotation(existing){const session=await getSession();if(!session)return;const v=values(),calc=calculateQuote(),client=clients.find(c=>c._id===v.client_id);if(!client){alert('Please select a client.');return}if(!calc.items.length){alert('Add at least one quotation item.');return}let quoteNumber=existing?.quote_number;if(!quoteNumber)try{quoteNumber=await nextQuoteNumber(session)}catch(e){alert(e.message);return}const payload={owner_id:session.user.id,quote_number:quoteNumber,client_id:client._id,client_code:client.id,client_name:client.business,client_contact:client.contact||null,client_email:client.email||null,client_phone:client.phone||null,quote_date:v.quote_date||today(),valid_until:v.valid_until||null,status:v.status,line_items:calc.items,subtotal:calc.subtotal,discount:calc.discount,vat_rate:calc.vatRate,vat_amount:calc.vat,total:calc.total,deposit_rate:calc.depositRate,deposit_amount:calc.deposit,balance_amount:calc.balance,notes:v.notes||null,terms:v.terms||null};const result=existing?await window.kasituSupabase.from('quotations').update(payload).eq('id',existing.id):await window.kasituSupabase.from('quotations').insert(payload);if(result.error){alert(result.error.message);return}await loadData();closeModal();renderQuotations()}
function closeModal(){modal.hidden=true;document.body.style.overflow=''}
function bindNavigation(){document.querySelectorAll('.nav-item[data-view]').forEach(btn=>btn.addEventListener('click',()=>{sidebar.classList.remove('open');render(btn.dataset.view);document.querySelectorAll('.nav-item').forEach(x=>x.classList.remove('active'));btn.classList.add('active')}));document.getElementById('mobileMenu').addEventListener('click',()=>sidebar.classList.toggle('open'));document.getElementById('modalClose').addEventListener('click',closeModal);modal.addEventListener('click',e=>{if(e.target===modal)closeModal()});document.getElementById('signOutButton').addEventListener('click',async()=>{await window.kasituSupabase.auth.signOut();window.location.replace('login.html')})}
function bindNavigationButtons(){document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>document.querySelector(`[data-view="${b.dataset.go}"]`)?.click()));document.querySelectorAll('[data-add="client"]').forEach(b=>b.addEventListener('click',()=>openModal('Client')));document.querySelectorAll('[data-add="lead"]').forEach(b=>b.addEventListener('click',()=>openModal('Lead')));document.querySelectorAll('[data-add="quotation"]').forEach(b=>b.addEventListener('click',()=>openModal('Quotation')));document.querySelectorAll('[data-add="invoice"]').forEach(b=>b.addEventListener('click',()=>openModal('Invoice')))}
function render(view){if(view==='clients')renderClients();else if(view==='leads')renderLeads();else if(view==='quotations')renderQuotations();else if(view==='invoices')renderInvoices();else renderDashboard();bindNavigationButtons()}
document.addEventListener('click',e=>{const cid=e.target.closest('[data-edit-client]')?.dataset.editClient;if(cid){openModal('Client',clients.find(c=>c.id===cid));return}const lid=e.target.closest('[data-edit-lead]')?.dataset.editLead;if(lid){openModal('Lead',leads.find(l=>l.id===lid));return}const qid=e.target.closest('[data-edit-quote]')?.dataset.editQuote;if(qid){openModal('Quotation',quotations.find(q=>q.id===qid));return}const ciid=e.target.closest('[data-create-invoice]')?.dataset.createInvoice;if(ciid){const q=quotations.find(x=>x.id===ciid);const client=q?clients.find(c=>c._id===q.client_id):null;openModal('Invoice',{quotation_id:q?.id||'',client_id:client?._id||'',client_name:client?.business||q?.client_name||'',items:q?.items||[],subtotal:q?.subtotal||0,discount:q?.discount||0,vat_rate:q?.vat_rate||0,total:q?.total||0,amount_paid:0,balance_due:q?.total||0,status:'Draft',invoice_date:today(),due_date:addDays(today(),7),notes:'Invoice created from '+(q?.quote_number||'quotation')});return}const iid=e.target.closest('[data-edit-invoice]')?.dataset.editInvoice;if(iid){openModal('Invoice',invoices.find(i=>i.id===iid));return}if(e.target.id==='cancelModal')closeModal()});
(async()=>{if(!window.supabase||!window.KASITU_SUPABASE_URL||!window.KASITU_SUPABASE_PUBLISHABLE_KEY){content.innerHTML='<div class="panel"><h2>Configuration missing</h2><p>Supabase configuration is missing.</p></div>';return}window.kasituSupabase=window.supabase.createClient(window.KASITU_SUPABASE_URL,window.KASITU_SUPABASE_PUBLISHABLE_KEY);const ok=await loadData();if(!ok)return;bindNavigation();renderDashboard()})();