/* KASITU Webs Business Manager — Phase 4 Payments */
const content=document.getElementById('appContent'),title=document.getElementById('pageTitle'),sidebar=document.getElementById('sidebar'),modal=document.getElementById('modalBackdrop'),modalTitle=document.getElementById('modalTitle'),form=document.getElementById('recordForm');
let clients=[],leads=[],quotations=[],invoices=[],payments=[],projects=[],maintenance=[],expenses=[],documents=[],projectsReady=true,maintenanceReady=true,expensesReady=true,documentsReady=true;
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));
const money=n=>`R${Number(n||0).toLocaleString('en-ZA',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const today=()=>new Date().toISOString().slice(0,10);
const addDays=(date,days)=>{const d=new Date(date+'T00:00:00');d.setDate(d.getDate()+days);return d.toISOString().slice(0,10)};
async function getSession(){const {data,error}=await window.kasituSupabase.auth.getSession();if(error||!data.session){window.location.replace('login.html');return null}return data.session}
async function loadData(){
 const session=await getSession();if(!session)return false;
 const [cr,lr,qr,ir,pr,xr,mr,er,dr]=await Promise.all([window.kasituSupabase.from('clients').select('*').order('created_at',{ascending:true}),window.kasituSupabase.from('leads').select('*').order('created_at',{ascending:false}),window.kasituSupabase.from('quotations').select('*').order('created_at',{ascending:false}),window.kasituSupabase.from('invoices').select('*').order('created_at',{ascending:false}),window.kasituSupabase.from('payments').select('*').order('payment_date',{ascending:false}).order('created_at',{ascending:false}),window.kasituSupabase.from('projects').select('*').order('created_at',{ascending:false}),window.kasituSupabase.from('maintenance').select('*').order('created_at',{ascending:false}),window.kasituSupabase.from('expenses').select('*').order('expense_date',{ascending:false}).order('created_at',{ascending:false}),window.kasituSupabase.from('documents').select('*').order('created_at',{ascending:false})]);
 if(cr.error||lr.error||qr.error||ir.error||pr.error){console.error(cr.error||lr.error||qr.error||ir.error||pr.error);content.innerHTML='<div class="panel"><h2>Database setup required</h2><p>Check your existing Business Manager database setup, then refresh.</p></div>';return false}
 projectsReady=!xr.error;if(xr.error)console.warn('Projects module setup required. Run projects-schema.sql in Supabase.',xr.error);
 clients=cr.data.map(c=>({id:c.client_code,business:c.business_name,contact:c.contact_name||'',email:c.email||'',phone:c.phone||'',service:c.service||'',status:c.status,notes:c.notes||'',_id:c.id}));
 leads=lr.data.map(l=>({id:l.id,business:l.business_name,contact:l.contact_name||'',phone:l.phone||'',email:l.email||'',service:l.service_requested||'',status:l.status,followUp:l.follow_up_date||'',source:l.source||'',notes:l.notes||'',date:l.created_at?.slice(0,10)||''}));
 quotations=qr.data.map(q=>({...q,items:Array.isArray(q.line_items)?q.line_items:[]}));
invoices=ir.data.map(i=>({...i,items:Array.isArray(i.line_items)?i.line_items:[]}));
payments=pr.data.map(p=>({...p}));
projects=projectsReady?(xr.data||[]).map(p=>({...p})):[];
 maintenanceReady=!mr.error;if(mr.error)console.warn('Maintenance module setup required. Run maintenance-schema.sql in Supabase.',mr.error);
 maintenance=maintenanceReady?(mr.data||[]).map(m=>({...m})):[];
 expensesReady=!er.error;if(er.error)console.warn('Expenses module setup required. Run expenses-schema.sql in Supabase.',er.error);
 expenses=expensesReady?(er.data||[]).map(x=>({...x})):[];
 documentsReady=!dr.error;if(dr.error)console.warn('Documents module setup required. Run documents-schema.sql in Supabase.',dr.error);
 documents=documentsReady?(dr.data||[]).map(d=>({...d})):[];
 return true
}
function renderDashboard(){
 title.textContent='Dashboard';const active=clients.filter(c=>c.status==='Active').length,openLeads=leads.filter(l=>!['Won','Lost'].includes(l.status)).length,approved=quotations.filter(q=>q.status==='Approved').length,outstanding=invoices.reduce((s,i)=>s+Number(i.balance_due||0),0);
 content.innerHTML=`<div class="hero-copy"><h2>Good morning, KASITU.</h2><p>Your business command centre — clients, leads and quotations in one place.</p></div>
 <div class="stats"><div class="stat"><div class="stat-label">Clients</div><div class="stat-value">${clients.length}</div><div class="stat-note">${active} active</div></div><div class="stat"><div class="stat-label">Open Leads</div><div class="stat-value">${openLeads}</div><div class="stat-note">Follow-ups to manage</div></div><div class="stat"><div class="stat-label">Quotations</div><div class="stat-value">${quotations.length}</div><div class="stat-note">${approved} approved</div></div><div class="stat"><div class="stat-label">Quoted Value</div><div class="stat-value">${money(quotations.reduce((s,q)=>s+Number(q.total||0),0))}</div><div class="stat-note">All quotation statuses</div></div><div class="stat"><div class="stat-label">Invoices</div><div class="stat-value">${invoices.length}</div><div class="stat-note">${money(outstanding)} outstanding</div></div><div class="stat"><div class="stat-label">Payments</div><div class="stat-value">${payments.length}</div><div class="stat-note">${money(payments.reduce((s,p)=>s+Number(p.amount||0),0))} recorded</div></div><div class="stat"><div class="stat-label">Expenses</div><div class="stat-value">${money(expenses.reduce((s,x)=>s+Number(x.amount||0),0))}</div><div class="stat-note">${money(expenses.filter(x=>(x.expense_date||'').slice(0,7)===today().slice(0,7)).reduce((s,x)=>s+Number(x.amount||0),0))} this month</div></div></div>
 <div class="grid-2"><div class="panel"><div class="panel-head"><h3>Recent Clients</h3><button class="btn" data-go="clients">View all</button></div>${clientTable(clients.slice(-5).reverse())}</div><div class="panel"><div class="panel-head"><h3>Recent Quotations</h3><button class="btn" data-go="quotations">View all</button></div>${quoteMini()}</div></div></div>`;bindNavigationButtons()
}
function clientTable(rows){if(!rows.length)return '<div class="empty">No clients yet.</div>';return `<div class="table-wrap"><table class="table"><thead><tr><th>Client</th><th>Service</th><th>Status</th></tr></thead><tbody>${rows.map(c=>`<tr><td><strong>${esc(c.business)}</strong><br><span style="color:var(--muted)">${esc(c.id)}</span></td><td>${esc(c.service||'—')}</td><td><span class="badge">${esc(c.status)}</span></td></tr>`).join('')}</tbody></table></div>`}
function leadSummary(){if(!leads.length)return '<div class="empty">No leads yet.<br><br><button class="btn primary" data-add="lead">Add your first lead</button></div>';const counts={New:0,Contacted:0,Quoted:0,Won:0,Lost:0};leads.forEach(l=>counts[l.status]=(counts[l.status]||0)+1);return Object.entries(counts).map(([k,v])=>`<div style="display:flex;justify-content:space-between;padding:12px 0;border-bottom:1px solid var(--border);font-size:12px"><span>${k}</span><strong>${v}</strong></div>`).join('')}
function renderClients(filter=''){title.textContent='Clients';const rows=clients.filter(c=>`${c.business} ${c.contact} ${c.email} ${c.id}`.toLowerCase().includes(filter.toLowerCase()));content.innerHTML=`<div class="section-head"><div><h2>Clients</h2><p>Your central client register and client IDs.</p></div><div style="display:flex;gap:9px"><input id="clientSearch" class="search" placeholder="Search clients..." value="${esc(filter)}"><button class="btn primary" data-add="client">+ Add Client</button></div></div><div class="panel">${clientTableDetailed(rows)}</div>`;document.getElementById('clientSearch').addEventListener('input',e=>renderClients(e.target.value))}
function clientTableDetailed(rows){if(!rows.length)return '<div class="empty">No matching clients.</div>';return `<div class="table-wrap"><table class="table"><thead><tr><th>Client ID</th><th>Business</th><th>Contact</th><th>Service</th><th>Status</th><th></th></tr></thead><tbody>${rows.map(c=>`<tr><td>${esc(c.id)}</td><td><strong>${esc(c.business)}</strong></td><td>${esc(c.contact||'—')}<br><span style="color:var(--muted)">${esc(c.phone||c.email||'')}</span></td><td>${esc(c.service||'—')}</td><td><span class="badge">${esc(c.status)}</span></td><td><button class="btn" data-edit-client="${esc(c.id)}">Edit</button></td></tr>`).join('')}</tbody></table></div>`}
function renderLeads(filter=''){title.textContent='Leads';const rows=leads.filter(l=>`${l.business} ${l.contact} ${l.service} ${l.status}`.toLowerCase().includes(filter.toLowerCase()));content.innerHTML=`<div class="section-head"><div><h2>Lead Pipeline</h2><p>Track enquiries from first contact to won or lost.</p></div><div style="display:flex;gap:9px"><input id="leadSearch" class="search" placeholder="Search leads..." value="${esc(filter)}"><button class="btn primary" data-add="lead">+ Add Lead</button></div></div><div class="panel">${leadTable(rows)}</div>`;document.getElementById('leadSearch').addEventListener('input',e=>renderLeads(e.target.value))}
function leadTable(rows){if(!rows.length)return '<div class="empty">No leads yet. Add every genuine enquiry here so no opportunity gets forgotten.</div>';return `<div class="table-wrap"><table class="table"><thead><tr><th>Date</th><th>Business / Person</th><th>Service</th><th>Status</th><th>Follow-up</th><th></th></tr></thead><tbody>${rows.map(l=>`<tr><td>${esc(l.date||'—')}</td><td><strong>${esc(l.business)}</strong><br><span style="color:var(--muted)">${esc(l.contact||'')}</span></td><td>${esc(l.service||'—')}</td><td><span class="badge">${esc(l.status)}</span></td><td>${esc(l.followUp||'—')}</td><td><button class="btn" data-edit-lead="${esc(l.id)}">Edit</button></td></tr>`).join('')}</tbody></table></div>`}

function invoiceStatus(s){return `<span class="invoice-status ${String(s||'Draft').toLowerCase().replace(/\s+/g,'-')}">${esc(s||'Draft')}</span>`}
function invoiceMini(){if(!invoices.length)return '<div class="empty">No invoices yet.<br><br><button class="btn primary" data-add="invoice">Create first invoice</button></div>';return invoices.slice(0,5).map(i=>`<div class="invoice-card"><div class="invoice-card-head"><div><div class="invoice-number">${esc(i.invoice_number)}</div><strong>${esc(i.client_name)}</strong></div><div style="text-align:right"><div class="invoice-total">${money(i.total)}</div>${invoiceStatus(i.status)}</div></div></div>`).join('')}
function renderInvoices(filter=''){title.textContent='Invoices';const rows=invoices.filter(i=>`${i.invoice_number} ${i.client_name} ${i.status}`.toLowerCase().includes(filter.toLowerCase()));content.innerHTML=`<div class="section-head"><div><h2>Invoices</h2><p>Create invoices from quotations, track balances and payment status.</p></div><div class="quote-toolbar"><input id="invoiceSearch" class="search" placeholder="Search invoices..." value="${esc(filter)}"><button class="btn primary" data-add="invoice">+ New Invoice</button></div></div><div class="panel">${invoiceTable(rows)}</div>`;document.getElementById('invoiceSearch').addEventListener('input',e=>renderInvoices(e.target.value))}
function invoiceTable(rows){if(!rows.length)return '<div class="empty">No invoices found. Create an invoice from a quotation.</div>';return `<div class="table-wrap"><table class="table"><thead><tr><th>Invoice</th><th>Client</th><th>Date</th><th>Due</th><th>Status</th><th>Total</th><th>Balance</th><th></th></tr></thead><tbody>${rows.map(i=>`<tr><td><strong>${esc(i.invoice_number)}</strong></td><td>${esc(i.client_name)}</td><td>${esc(i.invoice_date||'—')}</td><td>${esc(i.due_date||'—')}</td><td>${invoiceStatus(i.status)}</td><td><strong>${money(i.total)}</strong></td><td><strong>${money(i.balance_due)}</strong></td><td><button class="btn" data-edit-invoice="${esc(i.id)}">Edit</button></td></tr>`).join('')}</tbody></table></div>`}
function renderPayments(filter=''){
title.textContent='Payments';
const rows=payments.filter(p=>(p.payment_number+' '+(p.invoice_number||'')+' '+(p.client_name||'')+' '+(p.method||'')+' '+(p.reference||'')).toLowerCase().includes(filter.toLowerCase()));
content.innerHTML='<div class="section-head"><div><h2>Payments</h2><p>Record payments received and keep invoice balances up to date.</p></div><div class="quote-toolbar"><input id="paymentSearch" class="search" placeholder="Search payments..." value="'+esc(filter)+'"><button class="btn primary" data-add="payment">+ Record Payment</button></div></div><div class="panel">'+paymentTable(rows)+'</div>';
document.getElementById('paymentSearch').addEventListener('input',e=>renderPayments(e.target.value))}
function paymentTable(rows){if(!rows.length)return '<div class="empty">No payments recorded yet. Record your first payment against an invoice.</div>';return '<div class="table-wrap"><table class="table"><thead><tr><th>Payment</th><th>Invoice</th><th>Client</th><th>Date</th><th>Method</th><th>Reference</th><th>Amount</th><th></th></tr></thead><tbody>'+rows.map(p=>'<tr><td><strong>'+esc(p.payment_number)+'</strong></td><td>'+esc(p.invoice_number||'—')+'</td><td>'+esc(p.client_name||'—')+'</td><td>'+esc(p.payment_date||'—')+'</td><td>'+esc(p.method||'—')+'</td><td>'+esc(p.reference||'—')+'</td><td><strong>'+money(p.amount)+'</strong></td><td><button class="btn" data-edit-payment="'+esc(p.id)+'">Edit</button></td></tr>').join('')+'</tbody></table></div>'}
function paymentInvoiceOptions(selected=''){return '<option value="">Select an invoice...</option>'+invoices.map(i=>'<option value="'+esc(i.id)+'" '+(i.id===selected?'selected':'')+'>'+esc(i.invoice_number)+' — '+esc(i.client_name)+' — Balance '+money(i.balance_due)+'</option>').join('')}
function paymentForm(p={}){p=p||{};return '<div class="form-grid"><div class="field"><label>Invoice *</label><select name="invoice_id" required>'+paymentInvoiceOptions(p.invoice_id||'')+'</select></div><div class="field"><label>Payment number</label><input name="payment_number" value="'+esc(p.payment_number||'')+'" placeholder="Auto-generated on save" readonly></div><div class="field"><label>Payment date *</label><input type="date" name="payment_date" value="'+esc(p.payment_date||today())+'" required></div><div class="field"><label>Amount (R) *</label><input name="amount" type="number" min="0.01" step="0.01" value="'+Number(p.amount||0).toFixed(2)+'" required></div><div class="field"><label>Payment method *</label><select name="method">'+['EFT','Cash','Card','PayPal','Other'].map(x=>'<option '+(x===(p.method||'EFT')?'selected':'')+'>'+x+'</option>').join('')+'</select></div><div class="field"><label>Payment reference</label><input name="reference" value="'+esc(p.reference||'')+'" placeholder="Bank reference / receipt number"></div><div class="field" style="grid-column:1/-1"><label>Notes</label><textarea name="notes" placeholder="Optional payment notes">'+esc(p.notes||'')+'</textarea></div></div><div class="quote-summary" id="paymentSummary"></div><div class="form-actions"><button type="button" class="btn" id="cancelModal">Cancel</button><button class="btn primary">Save Payment</button></div>'}
function calculatePayment(){const invoiceId=form.querySelector('[name="invoice_id"]')?.value,invoice=invoices.find(i=>i.id===invoiceId),amount=Math.max(0,Number(form.querySelector('[name="amount"]')?.value||0));if(!invoice){form.querySelector('#paymentSummary').innerHTML='<div class="empty">Select an invoice to see its balance.</div>';return {invoice:null,amount:0,newPaid:0,newBalance:0}}const allRecorded=payments.filter(p=>p.invoice_id===invoice.id),recordedTotal=allRecorded.reduce((s,p)=>s+Number(p.amount||0),0),recordedBefore=allRecorded.filter(p=>p.id!==form.dataset.paymentId).reduce((s,p)=>s+Number(p.amount||0),0),openingPaid=Math.max(0,Number(invoice.amount_paid||0)-recordedTotal),previouslyPaid=openingPaid+recordedBefore,newPaid=Math.min(Number(invoice.total||0),previouslyPaid+amount),newBalance=Math.max(0,Number(invoice.total||0)-newPaid);form.querySelector('#paymentSummary').innerHTML='<div class="quote-summary-row"><span>Invoice total</span><strong>'+money(invoice.total)+'</strong></div><div class="quote-summary-row"><span>Previously paid</span><strong>'+money(openingPaid)+'</strong></div><div class="quote-summary-row"><span>This payment</span><strong>'+money(amount)+'</strong></div><div class="quote-summary-row total"><span>New balance</span><strong>'+money(newBalance)+'</strong></div>';return {invoice,amount,newPaid,newBalance}}
async function nextPaymentNumber(session){const {data,error}=await window.kasituSupabase.from('payments').select('payment_number').eq('owner_id',session.user.id);if(error)throw error;const nums=(data||[]).map(r=>Number(String(r.payment_number||'').match(/^KAS-P-\d{4}-(\d+)$/)?.[1]||0)).filter(Number.isFinite);return 'KAS-P-'+new Date().getFullYear()+'-'+String(Math.max(0,...nums)+1).padStart(3,'0')}
async function savePayment(existing){const session=await getSession();if(!session)return;const v=values(),calc=calculatePayment();if(!calc.invoice){alert('Please select an invoice.');return}if(calc.amount<=0){alert('Enter a payment amount greater than R0.');return}if(calc.amount>Number(calc.invoice.total||0)){alert('Payment cannot be greater than the invoice total.');return}let paymentNumber=existing?.payment_number;if(!paymentNumber)try{paymentNumber=await nextPaymentNumber(session)}catch(e){alert(e.message);return}const allRecorded=payments.filter(p=>p.invoice_id===calc.invoice.id),recordedTotal=allRecorded.reduce((s,p)=>s+Number(p.amount||0),0),recordedBefore=allRecorded.filter(p=>p.id!==existing?.id).reduce((s,p)=>s+Number(p.amount||0),0),openingPaid=Math.max(0,Number(calc.invoice.amount_paid||0)-recordedTotal),newPaid=Math.min(Number(calc.invoice.total||0),openingPaid+recordedBefore+calc.amount),newBalance=Math.max(0,Number(calc.invoice.total||0)-newPaid);let status=calc.invoice.status;if(newPaid>=Number(calc.invoice.total||0)&&Number(calc.invoice.total||0)>0)status='Paid';else if(newPaid>0)status='Partially Paid';else if(status==='Paid'||status==='Partially Paid')status='Draft';const payload={owner_id:session.user.id,payment_number:paymentNumber,invoice_id:calc.invoice.id,client_id:calc.invoice.client_id,client_code:calc.invoice.client_code,client_name:calc.invoice.client_name,invoice_number:calc.invoice.invoice_number,payment_date:v.payment_date||today(),amount:calc.amount,method:v.method||'EFT',reference:v.reference||null,notes:v.notes||null};const result=existing?await window.kasituSupabase.from('payments').update(payload).eq('id',existing.id):await window.kasituSupabase.from('payments').insert(payload);if(result.error){alert(result.error.message);return}const invoiceResult=await window.kasituSupabase.from('invoices').update({amount_paid:newPaid,balance_due:newBalance,status}).eq('id',calc.invoice.id);if(invoiceResult.error){alert(invoiceResult.error.message);return}await loadData();closeModal();renderPayments()}
function quotationOptions(selected=''){return '<option value="">Start without a quotation...</option>'+quotations.map(q=>`<option value="${esc(q.id)}" ${q.id===selected?'selected':''}>${esc(q.quote_number)} — ${esc(q.client_name)} — ${money(q.total)}</option>`).join('')}
function defaultInvoiceItems(i){return i?.items?.length?i.items:[{description:'',quantity:1,unit_price:0}]}
function invoiceForm(i={}){
 i=i||{};const valid=i.due_date||addDays(i.invoice_date||today(),7);
 return `<div class="form-grid"><div class="field"><label>Quotation</label><select name="quotation_id">${quotationOptions(i.quotation_id||'')}</select></div><div class="field"><label>Invoice number</label><input name="invoice_number" value="${esc(i.invoice_number||'')}" placeholder="Auto-generated on save" readonly></div><div class="field"><label>Invoice date *</label><input type="date" name="invoice_date" value="${esc(i.invoice_date||today())}" required></div><div class="field"><label>Due date</label><input type="date" name="due_date" value="${esc(valid)}"></div><div class="field"><label>Status</label><select name="status">${['Draft','Sent','Partially Paid','Paid','Overdue','Cancelled'].map(x=>`<option ${x===(i.status||'Draft')?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Amount paid (R)</label><input name="amount_paid" type="number" min="0" step="0.01" value="${Number(i.amount_paid||0).toFixed(2)}"></div><div class="field"><label>Discount (R)</label><input name="discount" type="number" min="0" step="0.01" value="${Number(i.discount||0).toFixed(2)}"></div><div class="field"><label>VAT rate (%)</label><input name="vat_rate" type="number" min="0" max="100" step="0.01" value="${Number(i.vat_rate||0)}"></div></div><div style="margin-top:20px"><div class="panel-head"><h3>Line items</h3><button type="button" class="btn" id="addInvoiceLine">+ Add item</button></div><div class="line-items" id="invoiceLines">${itemRows(defaultInvoiceItems(i)).replaceAll('name="item_qty"','name="invoice_qty"').replaceAll('name="item_price"','name="invoice_price"').replaceAll('name="item_description"','name="invoice_description"').replaceAll('name="item_total"','name="invoice_total"')}</div></div><div class="quote-summary" id="invoiceSummary"></div><div class="field" style="margin-top:20px"><label>Notes</label><textarea name="notes" placeholder="Optional invoice notes">${esc(i.notes||'')}</textarea></div><div class="field" style="margin-top:14px"><label>Terms & conditions</label><textarea name="terms" placeholder="Payment terms, due date, bank/payment details, etc.">${esc(i.terms||'Payment is due by the due date shown above. Please retain the invoice number as your payment reference.')}</textarea></div><div class="form-actions"><button type="button" class="btn" id="cancelModal">Cancel</button><button class="btn primary">Save Invoice</button></div>`}
function collectInvoiceItems(){return [...form.querySelectorAll('[data-line-row]')].map(row=>({description:row.querySelector('[name="invoice_description"]').value.trim(),quantity:Number(row.querySelector('[name="invoice_qty"]').value||0),unit_price:Number(row.querySelector('[name="invoice_price"]').value||0)})).filter(i=>i.description||i.unit_price>0)}
function calculateInvoice(){const items=collectInvoiceItems(),subtotal=items.reduce((s,i)=>s+i.quantity*i.unit_price,0),discount=Math.max(0,Number(form.querySelector('[name="discount"]')?.value||0)),taxable=Math.max(0,subtotal-discount),vatRate=Math.max(0,Number(form.querySelector('[name="vat_rate"]')?.value||0)),vat=taxable*vatRate/100,total=taxable+vat,paid=Math.min(total,Math.max(0,Number(form.querySelector('[name="amount_paid"]')?.value||0))),balance=Math.max(0,total-paid);form.querySelector('#invoiceSummary').innerHTML=`<div class="quote-summary-row"><span>Subtotal</span><strong>${money(subtotal)}</strong></div><div class="quote-summary-row"><span>Discount</span><strong>− ${money(discount)}</strong></div><div class="quote-summary-row"><span>VAT (${vatRate.toFixed(2)}%)</span><strong>${money(vat)}</strong></div><div class="quote-summary-row total"><span>Total</span><strong>${money(total)}</strong></div><div class="quote-summary-row"><span>Amount paid</span><strong>${money(paid)}</strong></div><div class="quote-summary-row"><span>Balance due</span><strong>${money(balance)}</strong></div>`;form.querySelectorAll('[data-line-row]').forEach(row=>{const qty=Number(row.querySelector('[name="invoice_qty"]').value||0),price=Number(row.querySelector('[name="invoice_price"]').value||0);row.querySelector('[name="invoice_total"]').value=money(qty*price)});return {items,subtotal,discount,vatRate,vat,total,paid,balance}}
async function nextInvoiceNumber(session){const {data,error}=await window.kasituSupabase.from('invoices').select('invoice_number').eq('owner_id',session.user.id);if(error)throw error;const nums=(data||[]).map(r=>Number(String(r.invoice_number||'').match(/^KAS-I-\d{4}-(\d+)$/)?.[1]||0)).filter(Number.isFinite);return `KAS-I-${new Date().getFullYear()}-${String(Math.max(0,...nums)+1).padStart(3,'0')}`}
const isUuid=v=>/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(String(v||''));
async function saveInvoice(existing){
 const session=await getSession();if(!session)return;
 const v=values(),calc=calculateInvoice();
 const quotationId=isUuid(v.quotation_id)?v.quotation_id:null;
 let quote=quotationId?quotations.find(q=>q.id===quotationId):null;
 const existingId=isUuid(existing?.id)?existing.id:null;
 let client=quote&&isUuid(quote.client_id)?clients.find(c=>c._id===quote.client_id):null;
 if(!client&&quote&&isUuid(quote.client_id)){
  const lookup=await window.kasituSupabase.from('clients').select('*').eq('id',quote.client_id).maybeSingle();
  if(lookup.error){alert('Could not load the quotation client: '+lookup.error.message);return}
  const c=lookup.data;
  if(c)client={id:c.client_code,business:c.business_name,contact:c.contact_name||'',email:c.email||'',phone:c.phone||'',service:c.service||'',status:c.status,notes:c.notes||'',_id:c.id};
 }
 if(!client&&existingId&&isUuid(existing.client_id))client=clients.find(c=>c._id===existing.client_id);
 if(!client){alert('Could not find a client record linked to this quotation. Please verify the client selection and try again.');return}
 if(!isUuid(client._id)){alert('The client record has an invalid UUID. Please edit/save the client first, then create the invoice again.');return}
 if(!calc.items.length){alert('Add at least one invoice item.');return}
 let invoiceNumber=existingId?existing.invoice_number:null;
 if(!invoiceNumber)try{invoiceNumber=await nextInvoiceNumber(session)}catch(e){alert(e.message);return}
 let status=v.status;
 if(calc.total>0&&calc.paid>=calc.total)status='Paid';
 else if(calc.paid>0)status='Partially Paid';
 else if(status==='Partially Paid'||status==='Paid')status='Draft';
 const payload={owner_id:session.user.id,invoice_number:invoiceNumber,quotation_id:quote?.id||null,client_id:client._id,client_code:client.id,client_name:client.business,client_contact:client.contact||null,client_email:client.email||null,client_phone:client.phone||null,invoice_date:v.invoice_date||today(),due_date:v.due_date||null,status,line_items:calc.items,subtotal:calc.subtotal,discount:calc.discount,vat_rate:calc.vatRate,vat_amount:calc.vat,total:calc.total,amount_paid:calc.paid,balance_due:calc.balance,notes:v.notes||null,terms:v.terms||null};
 const result=existingId?await window.kasituSupabase.from('invoices').update(payload).eq('id',existingId):await window.kasituSupabase.from('invoices').insert(payload);
 if(result.error){alert(result.error.message);return}
 await loadData();closeModal();renderInvoices()
}
function quoteStatus(s){return `<span class="quote-status ${String(s||'Draft').toLowerCase()}">${esc(s||'Draft')}</span>`}
function quoteMini(){if(!quotations.length)return '<div class="empty">No quotations yet.<br><br><button class="btn primary" data-add="quotation">Create first quotation</button></div>';return quotations.slice(0,5).map(q=>`<div class="quote-card"><div class="quote-card-head"><div><div class="quote-number">${esc(q.quote_number)}</div><strong>${esc(q.client_name)}</strong></div><div style="text-align:right"><div class="quote-total">${money(q.total)}</div>${quoteStatus(q.status)}</div></div></div>`).join('')}
function renderQuotations(filter=''){title.textContent='Quotations';const rows=quotations.filter(q=>`${q.quote_number} ${q.client_name} ${q.status}`.toLowerCase().includes(filter.toLowerCase()));content.innerHTML=`<div class="section-head"><div><h2>Quotations</h2><p>Create, track and edit professional quotations.</p></div><div class="quote-toolbar"><input id="quoteSearch" class="search" placeholder="Search quotations..." value="${esc(filter)}"><button class="btn primary" data-add="quotation">+ New Quotation</button></div></div><div class="panel">${quoteTable(rows)}</div>`;document.getElementById('quoteSearch').addEventListener('input',e=>renderQuotations(e.target.value))}
function quoteTable(rows){if(!rows.length)return '<div class="empty">No quotations found. Create your first quotation.</div>';return `<div class="table-wrap"><table class="table"><thead><tr><th>Quote</th><th>Client</th><th>Date</th><th>Valid until</th><th>Status</th><th>Total</th><th></th></tr></thead><tbody>${rows.map(q=>`<tr><td><strong>${esc(q.quote_number)}</strong></td><td>${esc(q.client_name)}</td><td>${esc(q.quote_date||'—')}</td><td>${esc(q.valid_until||'—')}</td><td>${quoteStatus(q.status)}</td><td><strong>${money(q.total)}</strong></td><td><button class="btn" data-edit-quote="${esc(q.id)}">Edit</button> <button class="btn" data-create-invoice="${esc(q.id)}">Invoice</button></td></tr>`).join('')}</tbody></table></div>`}
function clientOptions(selected=''){return '<option value="">Select a client...</option>'+clients.map(c=>`<option value="${esc(c._id)}" ${c._id===selected?'selected':''}>${esc(c.id)} — ${esc(c.business)}</option>`).join('')}
function defaultItems(q){return q?.items?.length?q.items:[{description:'Business Website',quantity:1,unit_price:4999}]}
function itemRows(items){return items.map(i=>`<div class="line-item" data-line-row><div class="field line-description"><label>Item / Service</label><input name="item_description" value="${esc(i.description||'')}"></div><div class="field"><label>Qty</label><input name="item_qty" type="number" min="1" step="1" value="${Number(i.quantity||1)}"></div><div class="field"><label>Unit price</label><input name="item_price" type="number" min="0" step="0.01" value="${Number(i.unit_price||0).toFixed(2)}"></div><div class="field"><label>Line total</label><input name="item_total" readonly value="${money(Number(i.quantity||1)*Number(i.unit_price||0))}"></div><button type="button" class="btn line-remove" data-remove-line aria-label="Remove item">×</button></div>`).join('')}
function quoteForm(q={}){
 q=q||{};const valid=q.valid_until||addDays(q.quote_date||today(),14);
 return `<div class="form-grid"><div class="field"><label>Client *</label><select name="client_id" required>${clientOptions(q.client_id||'')}</select></div><div class="field"><label>Quotation number</label><input name="quote_number" value="${esc(q.quote_number||'')}" placeholder="Auto-generated on save" readonly></div><div class="field"><label>Quotation date *</label><input type="date" name="quote_date" value="${esc(q.quote_date||today())}" required></div><div class="field"><label>Valid until</label><input type="date" name="valid_until" value="${esc(valid)}"></div><div class="field"><label>Status</label><select name="status">${['Draft','Sent','Approved','Rejected','Expired'].map(x=>`<option ${x===(q.status||'Draft')?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Deposit %</label><input name="deposit_rate" type="number" min="0" max="100" step="0.01" value="${Number(q.deposit_rate??50)}"></div><div class="field"><label>Discount (R)</label><input name="discount" type="number" min="0" step="0.01" value="${Number(q.discount||0).toFixed(2)}"></div><div class="field"><label>VAT rate (%)</label><input name="vat_rate" type="number" min="0" max="100" step="0.01" value="${Number(q.vat_rate||0)}"></div></div><div style="margin-top:20px"><div class="panel-head"><h3>Line items</h3><button type="button" class="btn" id="addQuoteLine">+ Add item</button></div><div class="line-items" id="quoteLines">${itemRows(defaultItems(q))}</div></div><div class="quote-summary" id="quoteSummary"></div><div class="field" style="margin-top:20px"><label>Notes</label><textarea name="notes" placeholder="Optional notes for the client">${esc(q.notes||'')}</textarea></div><div class="field" style="margin-top:14px"><label>Terms & conditions</label><textarea name="terms" placeholder="Payment terms, delivery terms, validity, etc.">${esc(q.terms||'Payment is due according to the agreed deposit and balance schedule. Quotation is valid until the date shown above.')}</textarea></div><div class="form-actions"><button type="button" class="btn" id="cancelModal">Cancel</button><button class="btn primary">Save Quotation</button></div>`
}
function collectQuoteItems(){return [...form.querySelectorAll('[data-line-row]')].map(row=>({description:row.querySelector('[name="item_description"]').value.trim(),quantity:Number(row.querySelector('[name="item_qty"]').value||0),unit_price:Number(row.querySelector('[name="item_price"]').value||0)})).filter(i=>i.description||i.unit_price>0)}
function calculateQuote(){const items=collectQuoteItems(),subtotal=items.reduce((s,i)=>s+i.quantity*i.unit_price,0),discount=Math.max(0,Number(form.querySelector('[name="discount"]')?.value||0)),taxable=Math.max(0,subtotal-discount),vatRate=Math.max(0,Number(form.querySelector('[name="vat_rate"]')?.value||0)),vat=taxable*vatRate/100,total=taxable+vat,depositRate=Math.min(100,Math.max(0,Number(form.querySelector('[name="deposit_rate"]')?.value||0))),deposit=total*depositRate/100,balance=Math.max(0,total-deposit);form.querySelector('#quoteSummary').innerHTML=`<div class="quote-summary-row"><span>Subtotal</span><strong>${money(subtotal)}</strong></div><div class="quote-summary-row"><span>Discount</span><strong>− ${money(discount)}</strong></div><div class="quote-summary-row"><span>VAT (${vatRate.toFixed(2)}%)</span><strong>${money(vat)}</strong></div><div class="quote-summary-row total"><span>Total</span><strong>${money(total)}</strong></div><div class="quote-summary-row"><span>Deposit (${depositRate.toFixed(2)}%)</span><strong>${money(deposit)}</strong></div><div class="quote-summary-row"><span>Balance due</span><strong>${money(balance)}</strong></div>`;form.querySelectorAll('[data-line-row]').forEach(row=>{const qty=Number(row.querySelector('[name="item_qty"]').value||0),price=Number(row.querySelector('[name="item_price"]').value||0);row.querySelector('[name="item_total"]').value=money(qty*price)});return {items,subtotal,discount,vatRate,vat,total,depositRate,deposit,balance}}

function maintenanceStatus(s){return '<span class="maintenance-status '+String(s||'Planned').toLowerCase().replace(/\s+/g,'-')+'">'+esc(s||'Planned')+'</span>'}
function renderMaintenance(filter=''){
 title.textContent='Maintenance';
 if(!maintenanceReady){content.innerHTML='<div class="panel"><h2>Maintenance setup needed</h2><p>Run the SQL in <strong>maintenance-schema.sql</strong> in your Supabase SQL Editor, then refresh this page. Your other Business Manager sections will continue to work.</p></div>';return}
 const rows=maintenance.filter(m=>(m.maintenance_number+' '+m.title+' '+m.client_name+' '+m.service_type+' '+m.status+' '+m.priority).toLowerCase().includes(filter.toLowerCase()));
 const active=maintenance.filter(m=>m.status==='Active').length,paused=maintenance.filter(m=>m.status==='Paused').length,due=maintenance.filter(m=>m.next_service_date&&m.next_service_date<=today()&&!['Completed','Cancelled'].includes(m.status)).length;
 content.innerHTML='<div class="stats"><div class="stat"><div class="stat-label">All plans</div><div class="stat-value">'+maintenance.length+'</div><div class="stat-note">Maintenance records</div></div><div class="stat"><div class="stat-label">Active</div><div class="stat-value">'+active+'</div><div class="stat-note">Currently maintained</div></div><div class="stat"><div class="stat-label">Paused</div><div class="stat-value">'+paused+'</div><div class="stat-note">Temporarily on hold</div></div><div class="stat"><div class="stat-label">Service due</div><div class="stat-value">'+due+'</div><div class="stat-note">Due today or overdue</div></div></div><div class="section-head"><div><h2>Maintenance</h2><p>Track client support plans, service schedules, fees and upcoming maintenance.</p></div><div class="quote-toolbar"><input id="maintenanceSearch" class="search" placeholder="Search maintenance..." value="'+esc(filter)+'"><button class="btn primary" data-add="maintenance">+ New Plan</button></div></div><div class="panel">'+maintenanceTable(rows)+'</div>';
 document.getElementById('maintenanceSearch').addEventListener('input',e=>renderMaintenance(e.target.value))
}
function maintenanceTable(rows){
 if(!rows.length)return '<div class="empty">No maintenance plans found. Add a plan to track ongoing client support.<br><br><button class="btn primary" data-add="maintenance">+ Create Maintenance Plan</button></div>';
 return '<div class="table-wrap"><table class="table"><thead><tr><th>Plan</th><th>Client</th><th>Service</th><th>Status</th><th>Next service</th><th>Fee</th><th></th></tr></thead><tbody>'+rows.map(m=>'<tr><td><strong>'+esc(m.title)+'</strong><br><span class="project-number">'+esc(m.maintenance_number)+'</span></td><td>'+esc(m.client_name)+'</td><td>'+esc(m.service_type||'—')+'<br><small>'+esc(m.billing_frequency||'One-time')+'</small></td><td>'+maintenanceStatus(m.status)+'</td><td>'+esc(m.next_service_date||'—')+'</td><td><strong>'+money(m.fee)+'</strong></td><td><button class="btn" data-edit-maintenance="'+esc(m.id)+'">Edit</button></td></tr>').join('')+'</tbody></table></div>'
}
function maintenanceForm(m={}){
 m=m||{};
 return '<div class="form-grid"><div class="field"><label>Plan / service title *</label><input name="title" required maxlength="180" value="'+esc(m.title||'')+'" placeholder="e.g. Website monthly maintenance"></div><div class="field"><label>Maintenance number</label><input name="maintenance_number" readonly value="'+esc(m.maintenance_number||'')+'" placeholder="Auto-generated on save"></div><div class="field"><label>Client *</label><select name="client_id" required>'+clientOptions(m.client_id||'')+'</select></div><div class="field"><label>Service type *</label><select name="service_type" required>'+['Website Maintenance','Security Alarm','Bluetooth Key Locator','Technical Support','Other'].map(x=>'<option '+(x===(m.service_type||'Website Maintenance')?'selected':'')+'>'+x+'</option>').join('')+'</select></div><div class="field"><label>Status</label><select name="status">'+['Planned','Active','Paused','Completed','Cancelled'].map(x=>'<option '+(x===(m.status||'Planned')?'selected':'')+'>'+x+'</option>').join('')+'</select></div><div class="field"><label>Priority</label><select name="priority">'+['Low','Normal','High','Urgent'].map(x=>'<option '+(x===(m.priority||'Normal')?'selected':'')+'>'+x+'</option>').join('')+'</select></div><div class="field"><label>Billing frequency</label><select name="billing_frequency">'+['One-time','Weekly','Monthly','Quarterly','Biannual','Annual','Custom'].map(x=>'<option '+(x===(m.billing_frequency||'Monthly')?'selected':'')+'>'+x+'</option>').join('')+'</select></div><div class="field"><label>Fee (R)</label><input name="fee" type="number" min="0" step="0.01" value="'+Number(m.fee||0).toFixed(2)+'"></div><div class="field"><label>Start date</label><input type="date" name="start_date" value="'+esc(m.start_date||today())+'"></div><div class="field"><label>Next service date</label><input type="date" name="next_service_date" value="'+esc(m.next_service_date||'')+'"></div><div class="field"><label>Last service date</label><input type="date" name="last_service_date" value="'+esc(m.last_service_date||'')+'"></div><div class="field full"><label>Description</label><textarea name="description" placeholder="Scope of service, inclusions and schedule">'+esc(m.description||'')+'</textarea></div><div class="field full"><label>Internal notes</label><textarea name="notes" placeholder="Service notes, reminders or next steps">'+esc(m.notes||'')+'</textarea></div></div><div class="form-actions"><button type="button" class="btn" id="cancelModal">Cancel</button><button class="btn primary">Save Maintenance Plan</button></div>'
}
async function nextMaintenanceNumber(session){
 const {data,error}=await window.kasituSupabase.from('maintenance').select('maintenance_number').eq('owner_id',session.user.id);
 if(error)throw error;
 const nums=(data||[]).map(r=>Number(String(r.maintenance_number||'').match(/^KAS-M-\d{4}-(\d+)$/)?.[1]||0)).filter(Number.isFinite);
 return 'KAS-M-'+new Date().getFullYear()+'-'+String(Math.max(0,...nums)+1).padStart(3,'0')
}
async function saveMaintenance(existing){
 if(!maintenanceReady){alert('Run maintenance-schema.sql in Supabase before saving maintenance plans.');return}
 const v=values(),session=await getSession();if(!session)return;
 const client=clients.find(c=>c._id===v.client_id);
 if(!client){alert('Please select a client for this maintenance plan.');return}
 let number=existing?.maintenance_number;
 if(!number)try{number=await nextMaintenanceNumber(session)}catch(e){alert(e.message);return}
 const payload={owner_id:session.user.id,maintenance_number:number,title:v.title.trim(),client_id:client._id,client_code:client.id,client_name:client.business,service_type:v.service_type||'Other',status:v.status||'Planned',priority:v.priority||'Normal',billing_frequency:v.billing_frequency||'Monthly',fee:Math.max(0,Number(v.fee||0)),start_date:v.start_date||null,next_service_date:v.next_service_date||null,last_service_date:v.last_service_date||null,description:v.description||null,notes:v.notes||null};
 const result=existing?await window.kasituSupabase.from('maintenance').update(payload).eq('id',existing.id):await window.kasituSupabase.from('maintenance').insert(payload);
 if(result.error){alert(result.error.message);return}
 await loadData();closeModal();renderMaintenance()
}


const expenseCategories=['Hosting & Domains','Internet & Data','Transport','Software & Subscriptions','Marketing & Advertising','Equipment & Supplies','Bank & Transaction Fees','Office & Admin','Training','Other'];
const expenseMethods=['EFT','Cash','Card','Debit Order','PayPal','Other'];
const safeReceiptUrl=value=>{try{const u=new URL(value);return ['https:','http:'].includes(u.protocol)?u.href:''}catch{return ''}};
function renderExpenses(filter='',category='All',period='all'){
 title.textContent='Expenses';if(!expensesReady){content.innerHTML='<div class="panel"><h2>Expenses setup needed</h2><p>Run <strong>expenses-schema.sql</strong> in Supabase SQL Editor, then refresh. Other sections will continue to work.</p></div>';return}
 const now=new Date(),month=today().slice(0,7),last=new Date(now.getFullYear(),now.getMonth()-1,1).toISOString().slice(0,7),year=today().slice(0,4);
 const rows=expenses.filter(x=>{const hay=[x.expense_number,x.title,x.category,x.vendor,x.payment_method,x.notes].join(' ').toLowerCase(),d=String(x.expense_date||'');return hay.includes(filter.toLowerCase())&&(category==='All'||x.category===category)&&(period==='all'||(period==='month'&&d.slice(0,7)===month)||(period==='last-month'&&d.slice(0,7)===last)||(period==='year'&&d.slice(0,4)===year))});
 const total=expenses.reduce((s,x)=>s+Number(x.amount||0),0),monthly=expenses.filter(x=>(x.expense_date||'').slice(0,7)===month).reduce((s,x)=>s+Number(x.amount||0),0),top=Object.entries(expenses.reduce((a,x)=>{a[x.category||'Other']=(a[x.category||'Other']||0)+Number(x.amount||0);return a},{})).sort((a,b)=>b[1]-a[1])[0];
 content.innerHTML='<div class="stats expense-stats"><div class="stat"><div class="stat-label">All expenses</div><div class="stat-value">'+money(total)+'</div><div class="stat-note">Total recorded spending</div></div><div class="stat"><div class="stat-label">This month</div><div class="stat-value">'+money(monthly)+'</div><div class="stat-note">'+esc(new Date().toLocaleDateString('en-ZA',{month:'long',year:'numeric'}))+'</div></div><div class="stat"><div class="stat-label">Records</div><div class="stat-value">'+expenses.length+'</div><div class="stat-note">Expenses logged</div></div><div class="stat"><div class="stat-label">Top category</div><div class="stat-value expense-top-category">'+esc(top?.[0]||'—')+'</div><div class="stat-note">'+(top?money(top[1]):'No expenses yet')+'</div></div></div><div class="section-head"><div><h2>Expenses</h2><p>Track business purchases, bills, payment methods and receipt links.</p></div><button class="btn primary" data-add="expense">+ Add Expense</button></div><div class="expense-toolbar"><input id="expenseSearch" class="search" placeholder="Search expenses..." value="'+esc(filter)+'"><select id="expenseCategory" class="search">'+['All',...expenseCategories].map(c=>'<option value="'+esc(c)+'" '+(c===category?'selected':'')+'>'+esc(c==='All'?'All categories':c)+'</option>').join('')+'</select><select id="expensePeriod" class="search"><option value="all" '+(period==='all'?'selected':'')+'>All time</option><option value="month" '+(period==='month'?'selected':'')+'>This month</option><option value="last-month" '+(period==='last-month'?'selected':'')+'>Last month</option><option value="year" '+(period==='year'?'selected':'')+'>This year</option></select></div><div class="panel"><div class="expense-filter-total"><span>Filtered total</span><strong>'+money(rows.reduce((s,x)=>s+Number(x.amount||0),0))+'</strong><span>'+rows.length+' record(s)</span></div>'+expenseTable(rows)+'</div>';
 const refresh=()=>renderExpenses(document.getElementById('expenseSearch').value,document.getElementById('expenseCategory').value,document.getElementById('expensePeriod').value);
 document.getElementById('expenseSearch').addEventListener('input',refresh);document.getElementById('expenseCategory').addEventListener('change',refresh);document.getElementById('expensePeriod').addEventListener('change',refresh)
}
function expenseTable(rows){
 if(!rows.length)return '<div class="empty">No expenses found. Add your first business expense to start tracking spending.<br><br><button class="btn primary" data-add="expense">+ Add Expense</button></div>';
 return '<div class="table-wrap"><table class="table expense-table"><thead><tr><th>Expense</th><th>Category</th><th>Date</th><th>Payment</th><th>Receipt</th><th>Amount</th><th>Actions</th></tr></thead><tbody>'+rows.map(x=>{const r=safeReceiptUrl(x.receipt_url);return '<tr><td><strong>'+esc(x.title)+'</strong><br><span class="project-number">'+esc(x.expense_number)+'</span>'+(x.vendor?'<br><small>'+esc(x.vendor)+'</small>':'')+'</td><td><span class="expense-category">'+esc(x.category||'Other')+'</span></td><td>'+esc(x.expense_date||'—')+'</td><td>'+esc(x.payment_method||'—')+'</td><td>'+(r?'<a class="receipt-link" href="'+esc(r)+'" target="_blank" rel="noopener noreferrer">View receipt ↗</a>':'—')+'</td><td><strong>'+money(x.amount)+'</strong></td><td><div class="expense-actions"><button class="btn" data-edit-expense="'+esc(x.id)+'">Edit</button> <button class="btn danger-btn" data-delete-expense="'+esc(x.id)+'">Delete</button></div></td></tr>'}).join('')+'</tbody></table></div>'
}
function expenseForm(x={}){x=x||{};return '<div class="form-grid"><div class="field"><label>Expense name *</label><input name="title" required maxlength="180" value="'+esc(x.title||'')+'" placeholder="e.g. Website hosting renewal"></div><div class="field"><label>Expense number</label><input name="expense_number" readonly value="'+esc(x.expense_number||'')+'" placeholder="Auto-generated on save"></div><div class="field"><label>Category *</label><select name="category" required>'+expenseCategories.map(c=>'<option '+(c===(x.category||'Hosting & Domains')?'selected':'')+'>'+esc(c)+'</option>').join('')+'</select></div><div class="field"><label>Amount (R) *</label><input name="amount" type="number" min="0.01" step="0.01" required value="'+(x.amount==null?'':Number(x.amount).toFixed(2))+'" placeholder="0.00"></div><div class="field"><label>Expense date *</label><input type="date" name="expense_date" required value="'+esc(x.expense_date||today())+'"></div><div class="field"><label>Payment method</label><select name="payment_method">'+expenseMethods.map(m=>'<option '+(m===(x.payment_method||'EFT')?'selected':'')+'>'+esc(m)+'</option>').join('')+'</select></div><div class="field"><label>Vendor / supplier</label><input name="vendor" maxlength="180" value="'+esc(x.vendor||'')+'" placeholder="e.g. Render, Canva, supplier"></div><div class="field"><label>Receipt link</label><input type="url" name="receipt_url" value="'+esc(x.receipt_url||'')+'" placeholder="https://..."></div><div class="field full"><label>Notes</label><textarea name="notes" placeholder="Purpose, purchase details or other notes">'+esc(x.notes||'')+'</textarea></div></div><div class="form-actions"><button type="button" class="btn" id="cancelModal">Cancel</button><button class="btn primary">Save Expense</button></div>'}
async function nextExpenseNumber(session){const {data,error}=await window.kasituSupabase.from('expenses').select('expense_number').eq('owner_id',session.user.id);if(error)throw error;const nums=(data||[]).map(r=>Number(String(r.expense_number||'').match(/^KAS-EX-\d{4}-(\d+)$/)?.[1]||0)).filter(Number.isFinite);return 'KAS-EX-'+new Date().getFullYear()+'-'+String(Math.max(0,...nums)+1).padStart(3,'0')}
async function saveExpense(existing){if(!expensesReady){alert('Run expenses-schema.sql in Supabase before saving expenses.');return}const v=values(),session=await getSession();if(!session)return;const amount=Number(v.amount||0);if(!v.title?.trim()){alert('Enter an expense name.');return}if(!Number.isFinite(amount)||amount<=0){alert('Enter an amount greater than R0.');return}const receipt=v.receipt_url?.trim()||'';if(receipt&&!safeReceiptUrl(receipt)){alert('Please enter a valid receipt link beginning with http:// or https://.');return}let number=existing?.expense_number;if(!number)try{number=await nextExpenseNumber(session)}catch(e){alert(e.message);return}const payload={owner_id:session.user.id,expense_number:number,title:v.title.trim(),category:v.category||'Other',amount,expense_date:v.expense_date||today(),payment_method:v.payment_method||'EFT',vendor:v.vendor?.trim()||null,receipt_url:receipt||null,notes:v.notes?.trim()||null};const result=existing?await window.kasituSupabase.from('expenses').update(payload).eq('id',existing.id):await window.kasituSupabase.from('expenses').insert(payload);if(result.error){alert(result.error.message);return}await loadData();closeModal();renderExpenses()}
async function deleteExpense(id){if(!expensesReady)return;const x=expenses.find(e=>e.id===id);if(!x)return;if(!confirm('Delete "'+x.title+'" ('+money(x.amount)+')? This cannot be undone.'))return;const {error}=await window.kasituSupabase.from('expenses').delete().eq('id',id);if(error){alert(error.message);return}await loadData();renderExpenses()}

const documentTypes=['Contract','Quotation','Invoice','Receipt','Project File','Client Brief','ID / Registration','Report','Other'];
const allowedDocumentTypes='.pdf,.doc,.docx,.xls,.xlsx,.csv,.txt,.png,.jpg,.jpeg,.webp';
function documentClientOptions(selected=''){return '<option value="">Not linked to a client</option>'+clients.map(c=>'<option value="'+esc(c._id)+'" '+(c._id===selected?'selected':'')+'>'+esc(c.business)+' ('+esc(c.id)+')</option>').join('')}
function renderDocuments(filter='',type='All'){
 title.textContent='Documents';if(!documentsReady){content.innerHTML='<div class="panel"><h2>Documents setup needed</h2><p>Run <strong>documents-schema.sql</strong> in Supabase SQL Editor, then refresh.</p></div>';return}
 const expiryLimit=addDays(today(),30),rows=documents.filter(d=>[d.document_number,d.title,d.document_type,d.client_name,d.file_name,d.notes].join(' ').toLowerCase().includes(filter.toLowerCase())&&(type==='All'||d.document_type===type));
 const attached=documents.filter(d=>d.client_id).length,expiring=documents.filter(d=>d.expiry_date&&d.expiry_date>=today()&&d.expiry_date<=expiryLimit).length;
 content.innerHTML='<div class="stats document-stats"><div class="stat"><div class="stat-label">Documents</div><div class="stat-value">'+documents.length+'</div><div class="stat-note">Files stored securely</div></div><div class="stat"><div class="stat-label">Client-linked</div><div class="stat-value">'+attached+'</div><div class="stat-note">Attached to client records</div></div><div class="stat"><div class="stat-label">Expiring soon</div><div class="stat-value">'+expiring+'</div><div class="stat-note">Due within 30 days</div></div><div class="stat"><div class="stat-label">Storage</div><div class="stat-value">Private</div><div class="stat-note">Access controlled</div></div></div><div class="section-head"><div><h2>Documents</h2><p>Keep client contracts, receipts, quotations and project files in one secure place.</p></div><button class="btn primary" data-add="document">+ Upload Document</button></div><div class="document-toolbar"><input id="documentSearch" class="search" placeholder="Search documents..." value="'+esc(filter)+'"><select id="documentType" class="search">'+['All',...documentTypes].map(t=>'<option value="'+esc(t)+'" '+(t===type?'selected':'')+'>'+esc(t==='All'?'All document types':t)+'</option>').join('')+'</select></div><div class="panel">'+documentTable(rows)+'</div>';
 document.getElementById('documentSearch').addEventListener('input',e=>renderDocuments(e.target.value,document.getElementById('documentType').value));
 document.getElementById('documentType').addEventListener('change',e=>renderDocuments(document.getElementById('documentSearch').value,e.target.value))
}
function documentTable(rows){if(!rows.length)return '<div class="empty">No documents found. Upload your first file.<br><br><button class="btn primary" data-add="document">+ Upload Document</button></div>';return '<div class="table-wrap"><table class="table document-table"><thead><tr><th>Document</th><th>Type</th><th>Client</th><th>Date</th><th>Expiry</th><th>File</th><th>Actions</th></tr></thead><tbody>'+rows.map(d=>'<tr><td><strong>'+esc(d.title)+'</strong><br><span class="project-number">'+esc(d.document_number)+'</span></td><td><span class="document-type-badge">'+esc(d.document_type)+'</span></td><td>'+esc(d.client_name||'—')+'</td><td>'+esc(d.document_date||'—')+'</td><td>'+esc(d.expiry_date||'—')+'</td><td><span class="document-file-name">'+esc(d.file_name||'No file')+'</span><br><small>'+formatFileSize(d.file_size)+'</small></td><td><div class="document-actions"><button class="btn" data-download-document="'+esc(d.id)+'">View / Download</button><button class="btn" data-edit-document="'+esc(d.id)+'">Edit</button><button class="btn danger-btn" data-delete-document="'+esc(d.id)+'">Delete</button></div></td></tr>').join('')+'</tbody></table></div>'}
function formatFileSize(size){const n=Number(size||0);if(!n)return '—';if(n<1024)return n+' B';if(n<1048576)return (n/1024).toFixed(1)+' KB';return (n/1048576).toFixed(2)+' MB'}
function documentForm(d={}){d=d||{};return '<div class="form-grid"><div class="field"><label>Document title *</label><input name="title" required maxlength="180" value="'+esc(d.title||'')+'" placeholder="e.g. Website maintenance agreement"></div><div class="field"><label>Document number</label><input name="document_number" readonly value="'+esc(d.document_number||'')+'" placeholder="Auto-generated on save"></div><div class="field"><label>Document type *</label><select name="document_type" required>'+documentTypes.map(t=>'<option '+(t===(d.document_type||'Contract')?'selected':'')+'>'+esc(t)+'</option>').join('')+'</select></div><div class="field"><label>Link to client</label><select name="client_id">'+documentClientOptions(d.client_id||'')+'</select></div><div class="field"><label>Document date</label><input type="date" name="document_date" value="'+esc(d.document_date||today())+'"></div><div class="field"><label>Expiry / renewal date</label><input type="date" name="expiry_date" value="'+esc(d.expiry_date||'')+'"></div><div class="field full"><label>Upload file '+(d.file_path?'(optional — leave blank to keep current file)':'*')+'</label><input type="file" name="document_file" accept="'+allowedDocumentTypes+'" '+(!d.file_path?'required':'')+'><small class="document-hint">PDF, Word, Excel, CSV, text or image files. Maximum 15 MB.</small>'+(d.file_name?'<div class="current-document-file">Current file: <strong>'+esc(d.file_name)+'</strong></div>':'')+'</div><div class="field full"><label>Notes</label><textarea name="notes" maxlength="5000" placeholder="Description, renewal details or other notes">'+esc(d.notes||'')+'</textarea></div></div><div class="form-actions"><button type="button" class="btn" id="cancelModal">Cancel</button><button class="btn primary">Save Document</button></div>'}
async function nextDocumentNumber(session){const {data,error}=await window.kasituSupabase.from('documents').select('document_number').eq('owner_id',session.user.id);if(error)throw error;const nums=(data||[]).map(r=>Number(String(r.document_number||'').match(/^KAS-D-\d{4}-(\d+)$/)?.[1]||0)).filter(Number.isFinite);return 'KAS-D-'+new Date().getFullYear()+'-'+String(Math.max(0,...nums)+1).padStart(3,'0')}
async function saveDocument(existing){if(!documentsReady){alert('Run documents-schema.sql in Supabase first.');return}const v=values(),session=await getSession();if(!session)return;const file=form.querySelector('[name="document_file"]')?.files?.[0]||null;if(!v.title?.trim()){alert('Enter a document title.');return}if(!existing&&!file){alert('Choose a file to upload.');return}if(file&&file.size>15*1024*1024){alert('This file is larger than 15 MB. Please choose a smaller file.');return}const client=clients.find(c=>c._id===v.client_id);let number=existing?.document_number;if(!number)try{number=await nextDocumentNumber(session)}catch(e){alert(e.message);return}const docId=existing?.id||crypto.randomUUID();let filePath=existing?.file_path||null,fileName=existing?.file_name||null,mimeType=existing?.mime_type||null,fileSize=existing?.file_size||null;if(file){const cleanName=file.name.normalize('NFKD').replace(/[^a-zA-Z0-9._-]+/g,'_').replace(/^\\.+/,'').slice(-180)||'upload';filePath=session.user.id+'/'+docId+'/'+Date.now()+'_'+cleanName;const uploaded=await window.kasituSupabase.storage.from('business-documents').upload(filePath,file,{contentType:file.type||'application/octet-stream',upsert:false});if(uploaded.error){alert('File upload failed: '+uploaded.error.message);return}fileName=file.name;mimeType=file.type||null;fileSize=file.size}const payload={owner_id:session.user.id,document_number:number,title:v.title.trim(),document_type:v.document_type||'Other',client_id:client?client._id:null,client_name:client?client.business:null,document_date:v.document_date||null,expiry_date:v.expiry_date||null,file_name:fileName,file_path:filePath,mime_type:mimeType,file_size:fileSize,notes:v.notes?.trim()||null};const result=existing?await window.kasituSupabase.from('documents').update(payload).eq('id',existing.id):await window.kasituSupabase.from('documents').insert({...payload,id:docId});if(result.error){if(filePath&&file)await window.kasituSupabase.storage.from('business-documents').remove([filePath]);alert(result.error.message);return}if(file&&existing?.file_path&&existing.file_path!==filePath)await window.kasituSupabase.storage.from('business-documents').remove([existing.file_path]);await loadData();closeModal();renderDocuments()}
async function downloadDocument(id){const d=documents.find(x=>x.id===id);if(!d?.file_path){alert('No file is attached to this document.');return}const tab=window.open('about:blank','_blank');const {data,error}=await window.kasituSupabase.storage.from('business-documents').createSignedUrl(d.file_path,60);if(error){if(tab)tab.close();alert('Could not open the file: '+error.message);return}if(tab)tab.location.href=data.signedUrl;else window.location.href=data.signedUrl}
async function deleteDocument(id){const d=documents.find(x=>x.id===id);if(!d)return;if(!confirm('Delete "'+d.title+'" and its stored file? This cannot be undone.'))return;if(d.file_path){const removed=await window.kasituSupabase.storage.from('business-documents').remove([d.file_path]);if(removed.error){alert('Could not remove the stored file: '+removed.error.message);return}}const {error}=await window.kasituSupabase.from('documents').delete().eq('id',id);if(error){alert(error.message);return}await loadData();renderDocuments()}
function projectStatus(s){return '<span class="project-status '+String(s||'Planning').toLowerCase().replace(/\s+/g,'-')+'">'+esc(s||'Planning')+'</span>'}
function renderProjects(filter=''){
 title.textContent='Projects';if(!projectsReady){content.innerHTML='<div class="panel"><h2>Projects setup needed</h2><p>Run the SQL in <strong>projects-schema.sql</strong> in your Supabase SQL Editor, then refresh this page. Your other Business Manager sections will continue to work.</p></div>';return}
 const rows=projects.filter(p=>(p.project_number+' '+p.project_name+' '+p.client_name+' '+p.status+' '+p.priority).toLowerCase().includes(filter.toLowerCase()));
 const active=projects.filter(p=>p.status==='In Progress').length,completed=projects.filter(p=>p.status==='Completed').length,overdue=projects.filter(p=>p.due_date&&p.due_date<today()&&!['Completed','Cancelled'].includes(p.status)).length;
 content.innerHTML='<div class="stats"><div class="stat"><div class="stat-label">All projects</div><div class="stat-value">'+projects.length+'</div><div class="stat-note">Projects in your register</div></div><div class="stat"><div class="stat-label">In progress</div><div class="stat-value">'+active+'</div><div class="stat-note">Currently underway</div></div><div class="stat"><div class="stat-label">Completed</div><div class="stat-value">'+completed+'</div><div class="stat-note">Delivered projects</div></div><div class="stat"><div class="stat-label">Past due</div><div class="stat-value">'+overdue+'</div><div class="stat-note">Needs a deadline review</div></div></div><div class="section-head"><div><h2>Projects</h2><p>Manage client work, deadlines, budgets and progress.</p></div><div class="quote-toolbar"><input id="projectSearch" class="search" placeholder="Search projects..." value="'+esc(filter)+'"><button class="btn primary" data-add="project">+ New Project</button></div></div><div class="panel">'+projectTable(rows)+'</div>';
 document.getElementById('projectSearch').addEventListener('input',e=>renderProjects(e.target.value))
}
function projectTable(rows){
 if(!rows.length)return '<div class="empty">No projects found. Create a project to track its progress and deadline.<br><br><button class="btn primary" data-add="project">+ Create Project</button></div>';
 return '<div class="table-wrap"><table class="table"><thead><tr><th>Project</th><th>Client</th><th>Status</th><th>Progress</th><th>Deadline</th><th>Budget</th><th></th></tr></thead><tbody>'+rows.map(p=>'<tr><td><strong>'+esc(p.project_name)+'</strong><br><span class="project-number">'+esc(p.project_number)+'</span></td><td>'+esc(p.client_name)+'</td><td>'+projectStatus(p.status)+'</td><td><div class="progress-track"><span style="width:'+Math.min(100,Math.max(0,Number(p.progress)||0))+'%"></span></div><small>'+Math.min(100,Math.max(0,Number(p.progress)||0))+'%</small></td><td>'+esc(p.due_date||'—')+'</td><td><strong>'+money(p.budget)+'</strong></td><td><button class="btn" data-edit-project="'+esc(p.id)+'">Edit</button></td></tr>').join('')+'</tbody></table></div>'
}
function projectForm(p={}){
 p=p||{};
 return '<div class="form-grid"><div class="field"><label>Project name *</label><input name="project_name" required maxlength="180" value="'+esc(p.project_name||'')+'" placeholder="e.g. Mumsy Braids website"></div><div class="field"><label>Project number</label><input name="project_number" readonly value="'+esc(p.project_number||'')+'" placeholder="Auto-generated on save"></div><div class="field"><label>Client *</label><select name="client_id" required>'+clientOptions(p.client_id||'')+'</select></div><div class="field"><label>Status</label><select name="status">'+['Planning','In Progress','On Hold','Completed','Cancelled'].map(x=>'<option '+(x===(p.status||'Planning')?'selected':'')+'>'+x+'</option>').join('')+'</select></div><div class="field"><label>Priority</label><select name="priority">'+['Low','Normal','High','Urgent'].map(x=>'<option '+(x===(p.priority||'Normal')?'selected':'')+'>'+x+'</option>').join('')+'</select></div><div class="field"><label>Progress (%)</label><input name="progress" type="number" min="0" max="100" step="1" value="'+Number(p.progress||0)+'" required></div><div class="field"><label>Start date</label><input type="date" name="start_date" value="'+esc(p.start_date||today())+'"></div><div class="field"><label>Due date</label><input type="date" name="due_date" value="'+esc(p.due_date||'')+'"></div><div class="field"><label>Budget (R)</label><input type="number" name="budget" min="0" step="0.01" value="'+Number(p.budget||0).toFixed(2)+'"></div><div class="field full"><label>Description</label><textarea name="description" placeholder="What needs to be delivered?">'+esc(p.description||'')+'</textarea></div><div class="field full"><label>Internal notes</label><textarea name="notes" placeholder="Milestones, next steps or reminders">'+esc(p.notes||'')+'</textarea></div></div><div class="form-actions"><button type="button" class="btn" id="cancelModal">Cancel</button><button class="btn primary">Save Project</button></div>'
}
async function nextProjectNumber(session){
 const {data,error}=await window.kasituSupabase.from('projects').select('project_number').eq('owner_id',session.user.id);
 if(error)throw error;
 const nums=(data||[]).map(r=>Number(String(r.project_number||'').match(/^KAS-PR-\d{4}-(\d+)$/)?.[1]||0)).filter(Number.isFinite);
 return 'KAS-PR-'+new Date().getFullYear()+'-'+String(Math.max(0,...nums)+1).padStart(3,'0')
}
async function saveProject(existing){
 if(!projectsReady){alert('Run projects-schema.sql in Supabase before saving projects.');return}
 const v=values(),session=await getSession();if(!session)return;
 const client=clients.find(c=>c._id===v.client_id);
 if(!client){alert('Please select a client for this project.');return}
 const progress=Math.min(100,Math.max(0,Number(v.progress||0)));
 let projectNumber=existing?.project_number;
 if(!projectNumber)try{projectNumber=await nextProjectNumber(session)}catch(e){alert(e.message);return}
 const payload={owner_id:session.user.id,project_number:projectNumber,project_name:v.project_name.trim(),client_id:client._id,client_code:client.id,client_name:client.business,description:v.description||null,status:v.status||'Planning',priority:v.priority||'Normal',start_date:v.start_date||null,due_date:v.due_date||null,budget:Math.max(0,Number(v.budget||0)),progress,notes:v.notes||null};
 if(payload.status==='Completed')payload.progress=100;
 const result=existing?await window.kasituSupabase.from('projects').update(payload).eq('id',existing.id):await window.kasituSupabase.from('projects').insert(payload);
 if(result.error){alert(result.error.message);return}
 await loadData();closeModal();renderProjects()
}

function openModal(type,existing=null){
 modal.hidden=false;document.body.style.overflow='hidden';modalTitle.textContent=existing?`Edit ${type}`:`Add New ${type}`;form.innerHTML=type==='Client'?clientForm(existing):type==='Lead'?leadForm(existing):type==='Quotation'?quoteForm(existing):type==='Invoice'?invoiceForm(existing):type==='Project'?projectForm(existing):type==='Maintenance'?maintenanceForm(existing):type==='Expense'?expenseForm(existing):type==='Document'?documentForm(existing):paymentForm(existing);requestAnimationFrame(()=>form.querySelector('input,select')?.focus());form.onsubmit=e=>{e.preventDefault();type==='Client'?saveClient(existing):type==='Lead'?saveLead(existing):type==='Quotation'?saveQuotation(existing):type==='Invoice'?saveInvoice(existing):type==='Project'?saveProject(existing):type==='Maintenance'?saveMaintenance(existing):type==='Expense'?saveExpense(existing):type==='Document'?saveDocument(existing):type==='Payment'?savePayment(existing):saveInvoice(existing)};document.getElementById('cancelModal')?.addEventListener('click',closeModal,{once:true});
 if(type==='Quotation'){document.getElementById('addQuoteLine').addEventListener('click',()=>{document.getElementById('quoteLines').insertAdjacentHTML('beforeend',itemRows([{description:'',quantity:1,unit_price:0}]));calculateQuote()});calculateQuote();form.addEventListener('input',e=>{if(e.target.closest('#quoteLines')||['discount','vat_rate','deposit_rate'].includes(e.target.name))calculateQuote()});form.addEventListener('click',e=>{if(e.target.closest('[data-remove-line]')){e.target.closest('[data-line-row]').remove();if(!document.querySelector('[data-line-row]'))document.getElementById('quoteLines').insertAdjacentHTML('beforeend',itemRows([{description:'',quantity:1,unit_price:0}]));calculateQuote()}})}
 if(type==='Invoice'){document.getElementById('addInvoiceLine').addEventListener('click',()=>{document.getElementById('invoiceLines').insertAdjacentHTML('beforeend',itemRows([{description:'',quantity:1,unit_price:0}]).replaceAll('name="item_qty"','name="invoice_qty"').replaceAll('name="item_price"','name="invoice_price"').replaceAll('name="item_description"','name="invoice_description"').replaceAll('name="item_total"','name="invoice_total"'));calculateInvoice()});calculateInvoice();form.addEventListener('input',e=>{if(e.target.closest('#invoiceLines')||['discount','vat_rate','amount_paid'].includes(e.target.name))calculateInvoice()});form.addEventListener('click',e=>{if(e.target.closest('[data-remove-line]')){e.target.closest('[data-line-row]').remove();if(!document.querySelector('#invoiceLines [data-line-row]'))document.getElementById('invoiceLines').insertAdjacentHTML('beforeend',itemRows([{description:'',quantity:1,unit_price:0}]).replaceAll('name="item_qty"','name="invoice_qty"').replaceAll('name="item_price"','name="invoice_price"').replaceAll('name="item_description"','name="invoice_description"').replaceAll('name="item_total"','name="invoice_total"'));calculateInvoice()}})}
if(type==='Payment'){form.dataset.paymentId=existing?.id||'';calculatePayment();form.addEventListener('input',e=>{if(e.target.name==='amount')calculatePayment()});form.addEventListener('change',e=>{if(e.target.name==='invoice_id')calculatePayment()})}
}
function clientForm(c={}){c=c||{};return `<div class="form-grid"><div class="field"><label>Business / Client name *</label><input name="business" required value="${esc(c.business)}"></div><div class="field"><label>Contact person</label><input name="contact" value="${esc(c.contact)}"></div><div class="field"><label>Email</label><input type="email" name="email" value="${esc(c.email)}"></div><div class="field"><label>Phone / WhatsApp</label><input name="phone" value="${esc(c.phone)}"></div><div class="field"><label>Service</label><input name="service" value="${esc(c.service)}" placeholder="e.g. Business Website"></div><div class="field"><label>Status</label><select name="status">${['Active','Prospect','Inactive'].map(x=>`<option ${x===(c.status||'Active')?'selected':''}>${x}</option>`).join('')}</select></div><div class="field" style="grid-column:1/-1"><label>Notes</label><textarea name="notes">${esc(c.notes)}</textarea></div></div><div class="form-actions"><button type="button" class="btn" id="cancelModal">Cancel</button><button class="btn primary">Save Client</button></div>`}
function leadForm(l={}){l=l||{};return `<div class="form-grid"><div class="field"><label>Business / Person *</label><input name="business" required value="${esc(l.business)}"></div><div class="field"><label>Contact person</label><input name="contact" value="${esc(l.contact)}"></div><div class="field"><label>Phone / WhatsApp</label><input name="phone" value="${esc(l.phone)}"></div><div class="field"><label>Email</label><input type="email" name="email" value="${esc(l.email)}"></div><div class="field"><label>Service requested</label><input name="service" value="${esc(l.service)}"></div><div class="field"><label>Status</label><select name="status">${['New','Contacted','Quoted','Won','Lost'].map(x=>`<option ${x===(l.status||'New')?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Follow-up date</label><input type="date" name="followUp" value="${esc(l.followUp)}"></div><div class="field"><label>Source</label><input name="source" value="${esc(l.source)}" placeholder="WhatsApp, website, referral..."></div><div class="field" style="grid-column:1/-1"><label>Notes</label><textarea name="notes">${esc(l.notes)}</textarea></div></div><div class="form-actions"><button type="button" class="btn" id="cancelModal">Cancel</button><button class="btn primary">Save Lead</button></div>`}
function values(){return Object.fromEntries(new FormData(form).entries())}
async function saveClient(existing){const v=values(),session=await getSession();if(!session)return;const base={owner_id:session.user.id,business_name:v.business,contact_name:v.contact||null,email:v.email||null,phone:v.phone||null,service:v.service||null,status:v.status,notes:v.notes||null};let result;if(existing)result=await window.kasituSupabase.from('clients').update({...base,client_code:existing.id}).eq('id',existing._id);else{const latest=await window.kasituSupabase.from('clients').select('client_code').eq('owner_id',session.user.id);if(latest.error){alert(latest.error.message);return}const used=(latest.data||[]).map(r=>Number(String(r.client_code||'').match(/^KAS-\d{4}-(\d+)$/)?.[1]||0)).filter(Number.isFinite);let next=Math.max(0,...used)+1;for(let i=0;i<5;i++){const code=`KAS-${new Date().getFullYear()}-${String(next).padStart(3,'0')}`;result=await window.kasituSupabase.from('clients').insert({...base,client_code:code});if(!result.error)break;if(!String(result.error.message||'').toLowerCase().includes('duplicate key'))break;next++}}if(result.error){alert(result.error.message);return}await loadData();closeModal();renderClients()}
async function saveLead(existing){const v=values(),session=await getSession();if(!session)return;const payload={owner_id:session.user.id,business_name:v.business,contact_name:v.contact||null,phone:v.phone||null,email:v.email||null,service_requested:v.service||null,status:v.status,follow_up_date:v.followUp||null,source:v.source||null,notes:v.notes||null};const result=existing?await window.kasituSupabase.from('leads').update(payload).eq('id',existing.id):await window.kasituSupabase.from('leads').insert(payload);if(result.error){alert(result.error.message);return}await loadData();closeModal();renderLeads()}
async function nextQuoteNumber(session){const {data,error}=await window.kasituSupabase.from('quotations').select('quote_number').eq('owner_id',session.user.id);if(error)throw error;const nums=(data||[]).map(r=>Number(String(r.quote_number||'').match(/^KAS-Q-\d{4}-(\d+)$/)?.[1]||0)).filter(Number.isFinite);return `KAS-Q-${new Date().getFullYear()}-${String(Math.max(0,...nums)+1).padStart(3,'0')}`}
async function saveQuotation(existing){const session=await getSession();if(!session)return;const v=values(),calc=calculateQuote(),client=clients.find(c=>c._id===v.client_id);if(!client){alert('Please select a client.');return}if(!calc.items.length){alert('Add at least one quotation item.');return}let quoteNumber=existing?.quote_number;if(!quoteNumber)try{quoteNumber=await nextQuoteNumber(session)}catch(e){alert(e.message);return}const payload={owner_id:session.user.id,quote_number:quoteNumber,client_id:client._id,client_code:client.id,client_name:client.business,client_contact:client.contact||null,client_email:client.email||null,client_phone:client.phone||null,quote_date:v.quote_date||today(),valid_until:v.valid_until||null,status:v.status,line_items:calc.items,subtotal:calc.subtotal,discount:calc.discount,vat_rate:calc.vatRate,vat_amount:calc.vat,total:calc.total,deposit_rate:calc.depositRate,deposit_amount:calc.deposit,balance_amount:calc.balance,notes:v.notes||null,terms:v.terms||null};const result=existing?await window.kasituSupabase.from('quotations').update(payload).eq('id',existing.id):await window.kasituSupabase.from('quotations').insert(payload);if(result.error){alert(result.error.message);return}await loadData();closeModal();renderQuotations()}
function closeModal(){modal.hidden=true;document.body.style.overflow=''}
function bindNavigation(){document.querySelectorAll('.nav-item[data-view]').forEach(btn=>btn.addEventListener('click',()=>{sidebar.classList.remove('open');render(btn.dataset.view);document.querySelectorAll('.nav-item').forEach(x=>x.classList.remove('active'));btn.classList.add('active')}));document.getElementById('mobileMenu').addEventListener('click',()=>sidebar.classList.toggle('open'));document.getElementById('modalClose').addEventListener('click',closeModal);modal.addEventListener('click',e=>{if(e.target===modal)closeModal()});document.getElementById('signOutButton').addEventListener('click',async()=>{await window.kasituSupabase.auth.signOut();window.location.replace('login.html')})}
function bindNavigationButtons(){document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>document.querySelector(`[data-view="${b.dataset.go}"]`)?.click()));document.querySelectorAll('[data-add="project"]').forEach(b=>b.addEventListener('click',()=>openModal('Project')));document.querySelectorAll('[data-add="client"]').forEach(b=>b.addEventListener('click',()=>openModal('Client')));document.querySelectorAll('[data-add="lead"]').forEach(b=>b.addEventListener('click',()=>openModal('Lead')));document.querySelectorAll('[data-add="quotation"]').forEach(b=>b.addEventListener('click',()=>openModal('Quotation')));document.querySelectorAll('[data-add="invoice"]').forEach(b=>b.addEventListener('click',()=>openModal('Invoice')));document.querySelectorAll('[data-add="payment"]').forEach(b=>b.addEventListener('click',()=>openModal('Payment')));document.querySelectorAll('[data-add="maintenance"]').forEach(b=>b.addEventListener('click',()=>openModal('Maintenance')));document.querySelectorAll('[data-add="expense"]').forEach(b=>b.addEventListener('click',()=>openModal('Expense')));document.querySelectorAll('[data-add="document"]').forEach(b=>b.addEventListener('click',()=>openModal('Document')))}
function render(view){if(view==='projects')renderProjects();else if(view==='maintenance')renderMaintenance();else if(view==='expenses')renderExpenses();else if(view==='documents')renderDocuments();else if(view==='clients')renderClients();else if(view==='leads')renderLeads();else if(view==='quotations')renderQuotations();else if(view==='invoices')renderInvoices();else if(view==='payments')renderPayments();else renderDashboard();bindNavigationButtons()}
document.addEventListener('click',e=>{const cid=e.target.closest('[data-edit-client]')?.dataset.editClient;if(cid){openModal('Client',clients.find(c=>c.id===cid));return}const lid=e.target.closest('[data-edit-lead]')?.dataset.editLead;if(lid){openModal('Lead',leads.find(l=>l.id===lid));return}const qid=e.target.closest('[data-edit-quote]')?.dataset.editQuote;if(qid){openModal('Quotation',quotations.find(q=>q.id===qid));return}const ciid=e.target.closest('[data-create-invoice]')?.dataset.createInvoice;if(ciid){const q=quotations.find(x=>x.id===ciid);const client=q?clients.find(c=>c._id===q.client_id):null;openModal('Invoice',{quotation_id:q?.id||'',client_id:client?._id||'',client_name:client?.business||q?.client_name||'',items:q?.items||[],subtotal:q?.subtotal||0,discount:q?.discount||0,vat_rate:q?.vat_rate||0,total:q?.total||0,amount_paid:0,balance_due:q?.total||0,status:'Draft',invoice_date:today(),due_date:addDays(today(),7),notes:'Invoice created from '+(q?.quote_number||'quotation')});return}const iid=e.target.closest('[data-edit-invoice]')?.dataset.editInvoice;if(iid){openModal('Invoice',invoices.find(i=>i.id===iid));return}const projid=e.target.closest('[data-edit-project]')?.dataset.editProject;if(projid){openModal('Project',projects.find(p=>p.id===projid));return}const maintid=e.target.closest('[data-edit-maintenance]')?.dataset.editMaintenance;if(maintid){openModal('Maintenance',maintenance.find(m=>m.id===maintid));return}const exid=e.target.closest('[data-edit-expense]')?.dataset.editExpense;if(exid){openModal('Expense',expenses.find(x=>x.id===exid));return}const delid=e.target.closest('[data-delete-expense]')?.dataset.deleteExpense;if(delid){deleteExpense(delid);return}const docid=e.target.closest('[data-edit-document]')?.dataset.editDocument;if(docid){openModal('Document',documents.find(d=>d.id===docid));return}const ddel=e.target.closest('[data-delete-document]')?.dataset.deleteDocument;if(ddel){deleteDocument(ddel);return}const dview=e.target.closest('[data-download-document]')?.dataset.downloadDocument;if(dview){downloadDocument(dview);return}const pid=e.target.closest('[data-edit-payment]')?.dataset.editPayment;if(pid){openModal('Payment',payments.find(p=>p.id===pid));return}if(e.target.id==='cancelModal')closeModal()});
(async()=>{if(!window.supabase||!window.KASITU_SUPABASE_URL||!window.KASITU_SUPABASE_PUBLISHABLE_KEY){content.innerHTML='<div class="panel"><h2>Configuration missing</h2><p>Supabase configuration is missing.</p></div>';return}window.kasituSupabase=window.supabase.createClient(window.KASITU_SUPABASE_URL,window.KASITU_SUPABASE_PUBLISHABLE_KEY);const ok=await loadData();if(!ok)return;bindNavigation();renderDashboard()})();